### ISSUE TITLE
construct_im behaviour with fixed-width integer vector

### ISSUE THREAD

**Issue by dvalenzu** [simongog/sdsl-lite#145]
If one attempt to build a (e.g.) a wavelet tree from a fixed-width integer vector, the behaviour is different than constructing the wavelet tree from a non fixed width integer sequence. In the former case,  the wavelet tree has one more element than the vector. Bellow a snippet of code.
(I tried only constructing a wavelet tree, it seems that will happen for other structures too)

Thanks,
Daniel

```
int_vector<64> x_vec(6, 0);    

for (size_t i = 0; i < 6; i++) {
  x_vec[i] = i;
}

cout << x_vec << endl;  // 1 2 3 4 5
wt_huff_int<rrr_vector<63>> wt;
construct_im(wt, x_vec, 8);
cout << "wt.sigma : " << wt.sigma << endl;  // 7
cout << "wt.size : " << wt.size() << endl;  // 7
 cout << wt << endl;  // 348 0 1 2 3 4 5
```

**Comment by Jabro** [comment]
Unfortunately the supposed fix won't compile on recent versions of the sdsl (`no matching function for call to ‘serialize(const sdsl::int_vector<64u>::raw_wrapper&, sdsl::osfstream&)’`)

When construction a huffman-shaped integer wavelet tree from a fixed-width integer, the result seems to be wrong:

   wt_huff_int<> wt;
   int_vector<8> vec = {3,12,4,4,5,1,6,4,2};
   construct_im(wt, vec);
   cout << "wt.sigma : " << wt.sigma << endl; //5
   cout << wt << endl;  //4 1 0 2 0 0 1 0 5 0 4 0 0 4 1 0 4 0 0 1 0 0 0 0

Regards & Thanks,
Jan
