### ISSUE TITLE
sdsl installation issue

### ISSUE THREAD

**Issue by sanjeevldc** [simongog/sdsl-lite#218]
Sir when i trying to install sdsl following errors:
In file included from /home/rubi/sdsl-lite-2.0.3/lib/uint128_t.cpp:1:0:
/home/rubi/sdsl-lite-2.0.3/build/lib/../include/sdsl/uint128_t.hpp:30:56: error: unable to emulate ‘TI’
/home/rubi/sdsl-lite-2.0.3/lib/uint128_t.cpp: In function ‘std::ostream& sdsl::operator<<(std::ostream&, const uint128_t&)’:
/home/rubi/sdsl-lite-2.0.3/lib/uint128_t.cpp:9:38: warning: right shift count >= width of type [enabled by default]
make[2]: *** [lib/CMakeFiles/sdsl.dir/uint128_t.cpp.o] Error 1
make[1]: *** [lib/CMakeFiles/sdsl.dir/all] Error 2
make: *** [all] Error 2
ERROR: Build failed.

**Comment by tb38** [comment]
Are you using a 64-bit operating system?

What do you get by the following commands?
getconf LONG_BIT
uname -m
cat /proc/cpuinfo | grep lm

**Comment by sanjeevldc** [comment]
Sir  by placing the command i got following:

getconf LONG_BIT
32
rubi@ubuntu:~$ uname -m
i686
rubi@ubuntu:~$ cat /proc/cpuinfo | grep lm
flags        : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca
cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt
pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc nonstop_tsc extd_apicid
aperfmperf pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic
cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt arat cpb
npt lbrv svm_lock nrip_save pausefilter
flags        : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca
cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt
pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc nonstop_tsc extd_apicid
aperfmperf pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic
cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt arat cpb
npt lbrv svm_lock nrip_save pausefilter


On Sun, Jan 25, 2015 at 5:37 PM, tb38 <notifications@github.com> wrote:

> Are you using a 64-bit operating system?
>
> What do you get by the following commands?
> getconf LONG_BIT
> uname -m
> cat /proc/cpuinfo | grep lm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simongog/sdsl-lite/issues/218#issuecomment-71369371>.
>



-- 



Sanjeev Gupta [LDCITS]
Mob: 09161292060
Email: sanjeev@ldcinstitute.com

**Comment by simongog** [comment]
Ok, it seems that you are using a 32-bit system. Currently SDSL only works on 64-bit systems.
