### ISSUE TITLE
coder_comma.hpp contains "conforming" C++11/non-conforming c++14 in init of codelentbllen

### ISSUE THREAD

**Issue by KellyJDavis** [simongog/sdsl-lite#222]
In the header `coder_comma.hpp`the `static const` variable `codelentbllen` is initialized as follows:

```C++
static const size_t codelentbllen = ceil(64 / log2(base));
```

The problem is `set::ceil` is not a `constexpr`function.

According to the original C++11 proposal, this would have been allowed. However, the final C++11 standard might/might not allow this under the [as-if](http://en.cppreference.com/w/cpp/language/as_if) rule. Under C++14 this is disallowed. (For more details see the discussion on [StackOverflow](http://stackoverflow.com/questions/27744079/is-it-a-conforming-compiler-extension-to-treat-non-constexpr-standard-library-fu).)

In light of this, there should be another means of initializing the `static const` variable `codelentbllen`.

PS: I found this after install upon running `make` in the `test` directory on OS X 10.10.2 with c++ version "Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)"

**Comment by simongog** [comment]
Thanks for the comment. I will modify the initialisation.
