### ISSUE TITLE
GPL licensed.

### ISSUE THREAD

**Issue by jbulow** [simongog/sdsl-lite#228]
I.e not usable for most of us.

Accident or intentional?

**Comment by mpetri** [comment]
In my view this was intentional as we want researches using the library to share their code which encourages good practice.

**Comment by simongog** [comment]
Yes, it was intentional. Some parts of this library (suffix array construction) also depend on GPL licensed code (libdivsufsort).
LGPL was not an option, as the library is a template library.

**Comment by jbulow** [comment]
Did you consider the boost license? ( http://www.boost.org/users/license.html )

**Comment by simongog** [comment]
Thanks for the pointer to the boost licence. This might be an appropriate alternative.

**Comment by ndryden** [comment]
> Yes, it was intentional. Some parts of this library (suffix array construction) also depend on GPL licensed code (libdivsufsort).

libdivsufsort is under the MIT license, not the GPL.

**Comment by pombredanne** [comment]
>  LGPL was not an option, as the library is a template library.

FWIW, you could also use the LGPL with a linking exception as used in GCC's libstc++

**Comment by harald-lang** [comment]
quite an older thread... lets me assume that a change to a non-invasive license is not going to happen?! :(

**Comment by simongog** [comment]
We are working on a new version, which is/will be BSD licenced: https://github.com/xxsds/sdsl-lite
