### ISSUE TITLE
compiling error of example code 

### ISSUE THREAD

**Issue by zhaoyanswill** [simongog/sdsl-lite#248]
Hi,

I tried example code:

    csa_wt<> fm_index;
    construct_im(fm_index, "mississippi!", 1);
    std::cout << "'si' occurs " << count(fm_index,"si") << " times.\n";

and got an error:

$ g++ -std=c++11 -I ~/include/ -L ~/lib sdsl_fm.cpp -lsdsl -ldivsufsort -ldivsufsort64
In file included from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/cassert:43:0,
                 from /u/yongzhao/include/sdsl/suffix_array_helper.hpp:26,
                 from /u/yongzhao/include/sdsl/csa_bitcompressed.hpp:26,
                 from /u/yongzhao/include/sdsl/suffix_arrays.hpp:28,
                 from sdsl_fm.cpp:2:
/u/yongzhao/include/sdsl/wt_ap.hpp: In member function ‘std::tuple<bool, long unsigned int, long unsigned int> sdsl::wt_ap<t_wt_byte, t_wt_int>::try_get_char_class_offset(sdsl::wt_ap<t_wt_byte, t_wt_int>::value_type) const’:
/u/yongzhao/include/sdsl/wt_ap.hpp:92:20: error: ‘i’ was not declared in this scope
             assert(i <= size());

After I commented this assertion out, the code works. Could you please check on it?

**Comment by simongog** [comment]
Thanks for pointing this out. It should work after the merge of this fix.
