### ISSUE TITLE
sd_vector construction from iterators fails for an empty input

### ISSUE THREAD

**Issue by jltsiren** [simongog/sdsl-lite#258]
The constructor `sd_vector::sd_vector(const t_itr begin,const t_itr end)` causes a segfault, if the input is empty (`begin == end`). The immediate cause is the line `m_size = *(end-1)+1;`, which determines the size of the vector by looking at the last 1-bit. It would be easy to solve the issue by building an empty vector if the input is empty. The easy solution is not always satisfactory, however.

A typical use for `sd_vector` is marking certain elements in an array (a vector, a bitvector, a string...). When we build it from a sorted list of marked positions, the size of the `sd_vector` depends on the last marked position, and it's often different from the size of the array. This is unintuitive and can cause problems. Having vector size as an optional third parameter would solve this problem.

**Comment by simongog** [comment]
Thanks for reporting. I will work on it.

**Comment by jltsiren** [comment]
Related to the second point: I'm testing in-place construction of `sd_vector` in my fork. I created a builder class that's initialized with the size of the vector and the number of 1-bits. The positions of the 1-bits are then given in strictly increasing order, without storing the set of positions explicitly at any point. When the construction is finished, the builder object is given to the `sd_vector` constructor, which grabs the contents of the builder.

I'll create a pull request when it has passed my tests. (Should there be any tests in SDSL itself? I'm not familiar with the test framework.) The patch will also fix the problem with an empty input.

**Comment by simongog** [comment]
Hi Jouni, nice solution. Can you pass my our test code as a gist so that I can integrate it to the test framework? Thanks and best, Simon

**Comment by jltsiren** [comment]
I don't have any self-contained test code at the moment. I'm only testing `sd_vector_builder` as a part of my BWT merging tool.

**Comment by jltsiren** [comment]
I implemented something by copying the test for the iterator constructor of `sd_vector`. Both tests are now in `sd_vector_test.cpp`. I'll create a pull request.

**Comment by jltsiren** [comment]
My patch also solved the original issue.
