### ISSUE TITLE
Compiling Problems 

### ISSUE THREAD

**Issue by flashkari** [simongog/sdsl-lite#260]
I installed all requirements of the project and followed the instructions on https://github.com/simongog/sdsl-lite but when I compiled the sample code, that was written on the page, I got the following error:

sdsl-lite$ g++ -std=c++11 -O3 -DNDEBUG -I ~/include -L ~/lib program.cpp -o program -lsdsl -ldivsufsort -ldivsufsort64
/tmp/ccOGLthZ.o: In function `void sdsl::write_structure<(sdsl::format_type)2, sdsl::csa_wt<sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<(unsigned char)1>, sdsl::rank_support_v<(unsigned char)1, (unsigned char)1>, sdsl::select_support_mcl<(unsigned char)1, (unsigned char)1>, sdsl::select_support_mcl<(unsigned char)0, (unsigned char)1>, sdsl::byte_tree<false> >, 32u, 64u, sdsl::sa_order_sa_sampling<(unsigned char)0>, sdsl::isa_sampling<(unsigned char)0>, sdsl::byte_alphabet> >(sdsl::csa_wt<sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<(unsigned char)1>, sdsl::rank_support_v<(unsigned char)1, (unsigned char)1>, sdsl::select_support_mcl<(unsigned char)1, (unsigned char)1>, sdsl::select_support_mcl<(unsigned char)0, (unsigned char)1>, sdsl::byte_tree<false> >, 32u, 64u, sdsl::sa_order_sa_sampling<(unsigned char)0>, sdsl::isa_sampling<(unsigned char)0>, sdsl::byte_alphabet> const&, std::ostream&)':
program.cpp:(.text._ZN4sdsl15write_structureILNS_11format_typeE2ENS_6csa_wtINS_5wt_pcINS_10huff_shapeENS_10int_vectorILh1EEENS_14rank_support_vILh1ELh1EEENS_18select_support_mclILh1ELh1EEENS9_ILh0ELh1EEENS_9byte_treeILb0EEEEELj32ELj64ENS_20sa_order_sa_samplingILh0EEENS_12isa_samplingILh0EEENS_13byte_alphabetEEEEEvRKT0_RSo[_ZN4sdsl15write_structureILNS_11format_typeE2ENS_6csa_wtINS_5wt_pcINS_10huff_shapeENS_10int_vectorILh1EEENS_14rank_support_vILh1ELh1EEENS_18select_support_mclILh1ELh1EEENS9_ILh0ELh1EEENS_9byte_treeILb0EEEEELj32ELj64ENS_20sa_order_sa_samplingILh0EEENS_12isa_samplingILh0EEENS_13byte_alphabetEEEEEvRKT0_RSo]+0x25a): undefined reference to `void sdsl::write_structure_tree<(sdsl::format_type)2>(sdsl::structure_tree_node const*, std::ostream&, unsigned long)'
collect2: error: ld returned 1 exit status

I  complied the bench mark code for wavelet tree and I got the following error:

sdsl-lite/benchmark/wavelet_trees$ make timing
Compiling build_BLCD_v
Compiling build_BLCD_RRR15
Compiling build_BLCD_RRR63
Compiling build_HUTU_v
Compiling build_HUTU_RRR15
Compiling build_HUTU_RRR63
Compiling build_HUFF_v
Compiling build_HUFF_RRR15
Compiling build_HUFF_RRR63
Compiling build_RLMN_v
Compiling build_RLMN_SD
Compiling build_WTAP
Download input from http://people.eng.unimelb.edu.au/sgog/data/enwiki-20130805-pages-articles1.int.sdsl.gz using curl
cd ../data; curl -O http://people.eng.unimelb.edu.au/sgog/data/enwiki-20130805-pages-articles1.int.sdsl.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20.8M  100 20.8M    0     0   947k      0  0:00:22  0:00:22 --:--:--  400k
Extract file ../data/enwiki-20130805-pages-articles1.int.sdsl.gz using gunzip
Running bin/build_BLCD_v on ENWIKISMLINT
Floating point exception (core dumped)
make: *** [results/BLCD_v.ENWIKISMLINT] Error 136
flashkar@ge123m05:~/Desktop/test/sdsl-lite/benchmark/wavelet_trees$ g++ -version
g++: error: unrecognized command line option ‘-version’
g++: fatal error: no input files
compilation terminated.

Do you how can I solve these problems?

**Comment by mpetri** [comment]
I just checked. The sample code is broken. I will fix it now. 

For the second problem I'm not sure what is the problem

**Comment by mpetri** [comment]
fixed in the newest version or just call ./install.sh twice
