### ISSUE TITLE
Setting Width of int_vector<0> is not working

### ISSUE THREAD

**Issue by danielsaad** [simongog/sdsl-lite#261]
Hello Simon and Matthias.
I'm having  an issue while using SDSL.
When int_vector<0> is declared, sdsl::util::expand_width does not work as planned.
The old_width value in this method is set to 64 during the int_vector initialization, so the condition is always false.
Also, the method  void width(uint8_t){ } is empty!

**Comment by mpetri** [comment]
64 is already the largest integer width that is support. also width() is only empty for fixed width int_vectors. for variable width int_vectors ( that is int_vector<0> ) width(uint8_t) is specialized in lib/int_vector.cpp

**Comment by danielsaad** [comment]
Thanks Matthias.
The problem was that i was using the default constructor of int_vector<0>
and hence, the width value was being set to 64.

If one uses the constructor which initializes the number of elements and the width it is possible to have a different width value.

Why it is  not a good idea to allow width changes when the int_vector<0> objects are built with the default constructor?

Best Regards

**Comment by mpetri** [comment]
I don't understand. you can "shrink" the width with for example bit_compress() which uses the minimum number of bits required to represent the bits in the bitvector.

**Comment by danielsaad** [comment]
The default constructor of int_vector<0> always initializes width as 64, the maximum width value. So that's the reason I had problems. My question is, why it is not a good idea to initialize the width with zero bits instead of making a two-step process (initialize with 64 bit width and the compress with bit_compress)?

Best Regards!

**Comment by simongog** [comment]
Hi Daniel, a vector of 0-width elements is a rather unusual case. This is the reason why the default is the maximum width. You can still use the third argument of the constructor to specify a width of 0 (so no two-step process).
Best, Simon

**Comment by danielsaad** [comment]
Thanks Simon and Matthias. I understand now. But it was kind of counter-intuitive for me, since I was expecting a zero bit width. I'm using now the tree-argument constructor with 1-bit width and dynamically extending the bit-vector as I need.
Thanks for the patience .

Best Regards.

**Comment by simongog** [comment]
No worries.
