### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [simongog/sdsl-lite#265]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [operator=()](https://github.com/simongog/sdsl-lite/blob/095fdac35283f99f3cb03f448c19c0fe25b68f6d/include/sdsl/select_support_mcl.hpp#L139 "An assignment operator")
* [bp_support_gg::copy](https://github.com/simongog/sdsl-lite/blob/095fdac35283f99f3cb03f448c19c0fe25b68f6d/include/sdsl/bp_support_gg.hpp#L92 "bp_support_gg::copy function")

**Comment by simongog** [comment]
Thanks @elfring. Will remove those checks.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/simongog/sdsl-lite/commit/5e10db7783ea9236fcc656806ae749cee6c68178 "Deletion of a few unnecessary checks").
