### ISSUE TITLE
sdsl-lite does not build on some architectures (error: unable to emulate 'TI')

### ISSUE THREAD

**Issue by thinred** [simongog/sdsl-lite#285]
Hi,
I packaged sdsl for Debian and the package was just accepted in experimental. I noticed that it fails to build on some architectures, notably on i386, but not only. See https://buildd.debian.org/status/logs.php?pkg=libsdsl

This has to do with some ABI details/sizes of variables.

Cheers,
Tomasz

**Comment by simongog** [comment]
Hi Tomasz,
thanks for letting me know. Is there a build log available displaying the error messages?

Best,

Simon

**Comment by thinred** [comment]
Yes, just click on red links, for example, https://buildd.debian.org/status/fetch.php?pkg=libsdsl&arch=hppa&ver=2.0.3-1&stamp=1446037836 :)

**Comment by thinred** [comment]
You may also like this overview: https://buildd.debian.org/status/package.php?p=libsdsl&suite=experimental. Note that some architectures haven't yet been tried. Moreover, I build libsdsl as dynamic library - I'm not sure if it interferes.

**Comment by simongog** [comment]
Thanks! It seems that I just have to check in cmake if the target platform is i386 and then switch to the non-built in 128-int class (https://github.com/simongog/sdsl-lite/blob/master/include/sdsl/uint128_t.hpp#L36). I'm wondering what is the standard way in cmake to do this check...

**Comment by thinred** [comment]
Not only i386 is problematic here, more exotic archs fail too. The most general fix would test whether this line with mode(TI) compiles without error, I think.
