### ISSUE TITLE
mode TI detection fails if sdsl-lite included as submodule in project

### ISSUE THREAD

**Issue by mpetri** [simongog/sdsl-lite#292]
The mode TI detection introduced by #286 fails if sdsl lite is included as a submodule / add_subdirectory in a parent project.

I think the solution is to change the line from:

```
try_compile(MODE_TI "${PROJECT_BINARY_DIR}" "${CMAKE_SOURCE_DIR}/CMakeModules/check_mode_ti.cpp")
```

to

```
try_compile(MODE_TI "${PROJECT_BINARY_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}/CMakeModules/check_mode_ti.cpp")
```

does this make sense @thinred ?

**Comment by thinred** [comment]
I think it does, although I haven't tested it. :)

**Comment by farruggia** [comment]
I came up with the same solution and it's working on my project. Please pull :-)

**Comment by simongog** [comment]
Merged now. Thanks guys!
