### ISSUE TITLE
I cannot figure out how to run the test suite

### ISSUE THREAD

**Issue by teythoon** [simongog/sdsl-lite#307]
The instructions how to run the test suite in the toplevel readme contradict the ones in tests/README.md.  Neither works for me, and I'm a bit lost here.

The top-level README.md says:

    To simply run all unit tests type
        cd sdsl-lite/test
        make

But:

    teythoon@europa /tmp/sdsl-lite/test (git)-[master] % make
    make: *** No targets specified and no makefile found.  Stop.

I'm doing an out-of-tree build, so I'm thinking maybe I need to do this in the build directory.  However:

    teythoon@europa /tmp/sdsl-lite/obj/test (git)-[master] % make ; echo $?
    0

That returns immediately.

The readme in test/ says:

    A call of make test in your cmake build directory will execute all tests.

But that doesn't do the trick for me either, neither in my build dir, nor in the test directory within that:

    teythoon@europa /tmp/sdsl-lite/obj (git)-[master] % make test
    teythoon@europa /tmp/sdsl-lite/obj (git)-[master] % make -C test test
    make: Entering directory '/tmp/sdsl-lite/obj/test'
    make: *** No rule to make target 'test'.  Stop.
    make: Leaving directory '/tmp/sdsl-lite/obj/test'

**Comment by simongog** [comment]
I guess it is not explicit enough that we assume that the install script (`./install.sh`) has to be executed before every other action -- including running the tests. After calling the install script everything should work fine; see the last jenkins run for an example http://141.3.24.109:8080/job/sdsl-lite-pull-request/94/consoleFull .

**Comment by teythoon** [comment]
I generally dislike install scripts, they tend to try to be extra clever or convenient, and install stuff in places I don't want.  Nevertheless, I did './install.sh /tmp/sdsl-target' and it finished successfully, and I still cannot figure out how to run the test suite from the documentation:

teythoon@europa /tmp/sdsl-lite (git)-[master] % cd build
teythoon@europa /tmp/sdsl-lite/build (git)-[master] % cd test
teythoon@europa /tmp/sdsl-lite/build/test (git)-[master] % make
teythoon@europa /tmp/sdsl-lite/build/test (git)-[master] % make test
make: *** No rule to make target 'test'.  Stop.
teythoon@europa /tmp/sdsl-lite/build/test (git)-[master] % ..
teythoon@europa /tmp/sdsl-lite/build (git)-[master] % make test
teythoon@europa /tmp/sdsl-lite/build (git)-[master] %

From the console log I see that 'make compile-test' and 'make test-sdsl' is executed, that however is not documented.

**Comment by simongog** [comment]
I forgot to update the documentation of the test after porting the code to Windows.
Now everything should be fine again. Thanks for the hint.
