### ISSUE TITLE
Wavelet tree examples build error

### ISSUE THREAD

**Issue by le-van** [simongog/sdsl-lite#311]
I tried to use wavelet trees examples (expl-14.cpp, expl-15.cpp, expl-16.cpp) but errors occurred with expl-14.cpp and expl-16.cpp. Could you please check these errors?

TakasuLab:tutorial lehongvan$ g++ -I/usr/local/include -std=c++11  -O3 -L/usr/local/lib -lsdsl -ldivsufsort -ldivsufsort64 -stdlib=libc++ expl-14.cpp 
Undefined symbols for architecture x86_64:
  "unsigned long long const& std::__1::get<0ul, unsigned long long, 2ul>(std::__1::array<unsigned long long, 2ul> const&)", referenced from:
      sdsl::empty(std::__1::array<unsigned long long, 2ul> const&) in libsdsl.a(wt_helper.cpp.o)
      sdsl::size(std::__1::array<unsigned long long, 2ul> const&) in libsdsl.a(wt_helper.cpp.o)
  "unsigned long long const& std::__1::get<1ul, unsigned long long, 2ul>(std::__1::array<unsigned long long, 2ul> const&)", referenced from:
      sdsl::empty(std::__1::array<unsigned long long, 2ul> const&) in libsdsl.a(wt_helper.cpp.o)
      sdsl::size(std::__1::array<unsigned long long, 2ul> const&) in libsdsl.a(wt_helper.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

TakasuLab:tutorial lehongvan$ g++ -I/usr/local/include -std=c++11  -O3 -L/usr/local/lib -lsdsl -ldivsufsort -ldivsufsort64 -stdlib=libc++ expl-15.cpp 

TakasuLab:tutorial lehongvan$ g++ -I/usr/local/include -std=c++11  -O3 -L/usr/local/lib -lsdsl -ldivsufsort -ldivsufsort64 -stdlib=libc++ expl-16.cpp 
Undefined symbols for architecture x86_64:
  "unsigned long long const& std::__1::get<0ul, unsigned long long, 2ul>(std::__1::array<unsigned long long, 2ul> const&)", referenced from:
      sdsl::empty(std::__1::array<unsigned long long, 2ul> const&) in libsdsl.a(wt_helper.cpp.o)
      sdsl::size(std::__1::array<unsigned long long, 2ul> const&) in libsdsl.a(wt_helper.cpp.o)
  "unsigned long long const& std::__1::get<1ul, unsigned long long, 2ul>(std::__1::array<unsigned long long, 2ul> const&)", referenced from:
      sdsl::empty(std::__1::array<unsigned long long, 2ul> const&) in libsdsl.a(wt_helper.cpp.o)
      sdsl::size(std::__1::array<unsigned long long, 2ul> const&) in libsdsl.a(wt_helper.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by simongog** [comment]
Compilation of tutorial examples was just added to the Travis CI build script:
https://travis-ci.org/simongog/sdsl-lite/builds/114053957

**Comment by le-van** [comment]
Thank you for your reply. I created a virtual machine using CentOS and built the library from the beginning. It worked without any errors. Seem that above errors caused by gcc version conflict on my Macbook.
