### ISSUE TITLE
Size of a Wavelet tree

### ISSUE THREAD

**Issue by le-van** [simongog/sdsl-lite#314]
I would like to calculate compression ratio when using Wavelet tree to compress data, so I need to calculate size of original data and size of the Wavelet tree. The function size() in Wavelet Trees only returns size of original data. Is there any way to calculate size of the Wavelet tree? I calculated the size of the bit vector of the Wavelet tree (e.g. wt_blcd.bv.size()) but I'm not sure that's the correct answer or not.

**Comment by mpetri** [comment]
you can use sdsl::size_in_bytes(wt) to determine the size of the structure.
