### ISSUE TITLE
Compile problem in wt_pc.hpp

### ISSUE THREAD

**Issue by rsharris** [simongog/sdsl-lite#315]
Howdy,

I cloned this for the first time today, and am getting a build fail in wt_pc.hpp.  I've appended to output of install, below.

I'm not proficient enough with cpp to understand the error.  Perhaps some compiler version incompatibility?

Note that although my path may look like I'm running on a mac, I'm actually running on some version of linux.

Bob H

$ date
Tue Mar 15

$ git clone https://github.com/simongog/sdsl-lite.git
Cloning into 'sdsl-lite'...
remote: Counting objects: 12978, done.
remote: Total 12978 (delta 0), reused 0 (delta 0), pack-reused 12978
Receiving objects: 100% (12978/12978), 9.04 MiB | 11.45 MiB/s, done.
Resolving deltas: 100% (7414/7414), done.

$ cd sdsl-lite
$ ./install.sh /Users/bharris/sdsl/install
Library will be installed in '/Users/bharris/sdsl/install'
Copy pre-commit into .git/hooks
-- The CXX compiler identification is GNU 4.7.2
-- The C compiler identification is GNU 4.7.2
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Compiler is recent enough to support C++11.
-- Performing Test HAVE_GCC_STD=C__11__WALL__WEXTRA___DNDEBUG
-- Performing Test HAVE_GCC_STD=C__11__WALL__WEXTRA___DNDEBUG - Success
-- Performing Test HAVE_GCC_O3__FFAST_MATH__FUNROLL_LOOPS
-- Performing Test HAVE_GCC_O3__FFAST_MATH__FUNROLL_LOOPS - Success
-- Performing Test HAVE_GCC_MSSE4.2
-- Performing Test HAVE_GCC_MSSE4.2 - Success
CMake Warning (dev) at external/libdivsufsort/CMakeLists.txt:7 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test HAVE_GCC_WALL
-- Performing Test HAVE_GCC_WALL - Success
-- Performing Test HAVE_GCC_FOMIT_FRAME_POINTER
-- Performing Test HAVE_GCC_FOMIT_FRAME_POINTER - Success
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Performing Test HAVE_INLINE
-- Performing Test HAVE_INLINE - Success
-- Performing Test HAVE___INLINE
-- Performing Test HAVE___INLINE - Success
-- Performing Test HAVE___INLINE__
-- Performing Test HAVE___INLINE__ - Success
-- Performing Test HAVE___DECLSPEC_DLLEXPORT_
-- Performing Test HAVE___DECLSPEC_DLLEXPORT_ - Failed
-- Performing Test HAVE___DECLSPEC_DLLIMPORT_
-- Performing Test HAVE___DECLSPEC_DLLIMPORT_ - Failed
-- Check size of uint8_t
-- Check size of uint8_t - done
-- Check size of int32_t
-- Check size of int32_t - done
-- Looking for PRId32
-- Looking for PRId32 - found
-- Check size of int64_t
-- Check size of int64_t - done
-- Looking for PRId64
-- Looking for PRId64 - found
CMake Warning (dev) at external/googletest/CMakeLists.txt:42 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /Users/bharris/python/linux-x86_64/Python-2.7.10/python (found version "2.7.10") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for C++ include cstdio
-- Looking for C++ include cstdio - found
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/bharris/sdsl/sdsl-lite/build
Scanning dependencies of target sdsl
[  0%] Building CXX object lib/CMakeFiles/sdsl.dir/bits.cpp.o
[  0%] Building CXX object lib/CMakeFiles/sdsl.dir/bp_support_algorithm.cpp.o
[ 14%] Building CXX object lib/CMakeFiles/sdsl.dir/coder_elias_delta.cpp.o
[ 14%] Building CXX object lib/CMakeFiles/sdsl.dir/coder_elias_gamma.cpp.o
[ 14%] Building CXX object lib/CMakeFiles/sdsl.dir/coder_fibonacci.cpp.o
[ 14%] Building CXX object lib/CMakeFiles/sdsl.dir/config.cpp.o
[ 28%] Building CXX object lib/CMakeFiles/sdsl.dir/construct_config.cpp.o
[ 28%] Building CXX object lib/CMakeFiles/sdsl.dir/construct_isa.cpp.o
[ 28%] Building CXX object lib/CMakeFiles/sdsl.dir/construct_lcp.cpp.o
In file included from /Users/bharris/sdsl/sdsl-lite/build/lib/../include/sdsl/wt_huff.hpp:25:0,
                 from /Users/bharris/sdsl/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:33,
                 from /Users/bharris/sdsl/sdsl-lite/lib/construct_lcp.cpp:6:
/Users/bharris/sdsl/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp: In instantiation of ‘std::array<typename t_tree_strat::type<sdsl::wt_pc<t_shape, t_bitvector, t_rank, t_select, t_select_zero, t_tree_strat> >::node_type, 2ul> sdsl::wt_pc<t_shape, t_bitvector, t_rank, t_select, t_select_zero, t_tree_strat>::expand(const node_type&) const [with t_shape = sdsl::huff_shape; t_bitvector = sdsl::int_vector<1u>; t_rank = sdsl::rank_support_v<1u, 1u>; t_select = sdsl::select_support_scan<1u>; t_select_zero = sdsl::select_support_scan<0u>; t_tree_strat = sdsl::byte_tree<>; typename t_tree_strat::type<sdsl::wt_pc<t_shape, t_bitvector, t_rank, t_select, t_select_zero, t_tree_strat> >::node_type = short unsigned int; sdsl::wt_pc<t_shape, t_bitvector, t_rank, t_select, t_select_zero, t_tree_strat>::node_type = short unsigned int]’:
/Users/bharris/sdsl/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:143:40:   required from ‘void sdsl::_interval_symbols_rec(const t_wt&, sdsl::range_type, typename t_wt::size_type&, std::vector<typename t_wt::value_type>&, std::vector<typename t_wt::size_type>&, std::vector<typename t_wt::size_type>&, const typename t_wt::node_type&) [with t_wt = sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >; sdsl::range_type = std::array<long unsigned int, 2ul>; typename t_wt::size_type = long unsigned int; typename t_wt::value_type = unsigned char; typename t_wt::node_type = short unsigned int]’
/Users/bharris/sdsl/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:176:9:   required from ‘void sdsl::_interval_symbols(const t_wt&, typename t_wt::size_type, typename t_wt::size_type, typename t_wt::size_type&, std::vector<typename t_wt::value_type>&, std::vector<typename t_wt::size_type>&, std::vector<typename t_wt::size_type>&) [with t_wt = sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >; typename t_wt::size_type = long unsigned int; typename t_wt::value_type = unsigned char; typename t_wt::size_type = long unsigned int]’
/Users/bharris/sdsl/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:217:9:   required from ‘void sdsl::interval_symbols(const t_wt&, typename t_wt::size_type, typename t_wt::size_type, typename t_wt::size_type&, std::vector<typename t_wt::value_type>&, std::vector<typename t_wt::size_type>&, std::vector<typename t_wt::size_type>&) [with t_wt = sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >; typename t_wt::size_type = long unsigned int; typename t_wt::value_type = unsigned char; typename t_wt::size_type = long unsigned int]’
/Users/bharris/sdsl/sdsl-lite/lib/construct_lcp.cpp:681:68:   required from here
/Users/bharris/sdsl/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:729:57: error: could not convert ‘{((const sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >*)this)->sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >::m_tree.sdsl::_byte_tree<t_dfs_shape, t_wt>::child<false, sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> > >(((int)v), 0), ((const sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >*)this)->sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >::m_tree.sdsl::_byte_tree<t_dfs_shape, t_wt>::child<false, sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> > >(((int)v), 1)}’ from ‘<brace-enclosed initializer list>’ to ‘std::array<short unsigned int, 2ul>’
/Users/bharris/sdsl/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp: In instantiation of ‘std::array<std::array<long unsigned int, 2ul>, 2ul> sdsl::wt_pc<t_shape, t_bitvector, t_rank, t_select, t_select_zero, t_tree_strat>::expand(const node_type&, const range_type&) const [with t_shape = sdsl::huff_shape; t_bitvector = sdsl::int_vector<1u>; t_rank = sdsl::rank_support_v<1u, 1u>; t_select = sdsl::select_support_scan<1u>; t_select_zero = sdsl::select_support_scan<0u>; t_tree_strat = sdsl::byte_tree<>; sdsl::wt_pc<t_shape, t_bitvector, t_rank, t_select, t_select_zero, t_tree_strat>::node_type = short unsigned int; sdsl::range_type = std::array<long unsigned int, 2ul>]’:
/Users/bharris/sdsl/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:144:43:   required from ‘void sdsl::_interval_symbols_rec(const t_wt&, sdsl::range_type, typename t_wt::size_type&, std::vector<typename t_wt::value_type>&, std::vector<typename t_wt::size_type>&, std::vector<typename t_wt::size_type>&, const typename t_wt::node_type&) [with t_wt = sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >; sdsl::range_type = std::array<long unsigned int, 2ul>; typename t_wt::size_type = long unsigned int; typename t_wt::value_type = unsigned char; typename t_wt::node_type = short unsigned int]’
/Users/bharris/sdsl/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:176:9:   required from ‘void sdsl::_interval_symbols(const t_wt&, typename t_wt::size_type, typename t_wt::size_type, typename t_wt::size_type&, std::vector<typename t_wt::value_type>&, std::vector<typename t_wt::size_type>&, std::vector<typename t_wt::size_type>&) [with t_wt = sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >; typename t_wt::size_type = long unsigned int; typename t_wt::value_type = unsigned char; typename t_wt::size_type = long unsigned int]’
/Users/bharris/sdsl/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:217:9:   required from ‘void sdsl::interval_symbols(const t_wt&, typename t_wt::size_type, typename t_wt::size_type, typename t_wt::size_type&, std::vector<typename t_wt::value_type>&, std::vector<typename t_wt::size_type>&, std::vector<typename t_wt::size_type>&) [with t_wt = sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >; typename t_wt::size_type = long unsigned int; typename t_wt::value_type = unsigned char; typename t_wt::size_type = long unsigned int]’
/Users/bharris/sdsl/sdsl-lite/lib/construct_lcp.cpp:681:68:   required from here
/Users/bharris/sdsl/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:804:13: error: could not convert ‘{{{left_sp, ((left_sp + left_size) + 18446744073709551615ul)}, {right_sp, ((right_sp + right_size) + 18446744073709551615ul)}}}’ from ‘<brace-enclosed initializer list>’ to ‘std::array<std::array<long unsigned int, 2ul>, 2ul>’
make[3]: *** [lib/CMakeFiles/sdsl.dir/construct_lcp.cpp.o] Error 1
make[2]: *** [lib/CMakeFiles/sdsl.dir/all] Error 2
make[1]: *** [lib/CMakeFiles/sdsl.dir/rule] Error 2
make: *** [sdsl] Error 2
ERROR: Build failed.
brubeck:sdsl-lite$

**Comment by simongog** [comment]
A recent change forces the gcc version to be >= 4.9. I will update the README file.

**Comment by rsharris** [comment]
Cool, thanks.
