### ISSUE TITLE
"Unknown file" when constructing from raw pointer

### ISSUE THREAD

**Issue by pdinklag** [simongog/sdsl-lite#316]
I am trying to construct a suffix array for a text already stored in memory.
Given `const uint8_t* ptr` and `size_t` len, this is my approach:

    //Debug output
    DLOG(INFO) << "Input (" << len << "): \"" << ptr << "\"";
    DLOG(INFO) << "Terminated by: " << uint32_t(ptr[len]);

    //Construct SA
    sdsl::csa_sada<> sa;
    sdsl::construct_im(sa, ptr);

It yields the following output in my test case:

    I0316 09:30:58.699618 17995 LZ77SSLCPCompressor.hpp:43] Input (6): "banana"
    I0316 09:30:58.699645 17995 LZ77SSLCPCompressor.hpp:44] Terminated by: 0
    unknown file: Failure
    C++ exception with description "Error: File "@17995_0" contains zero symbol." thrown in the test body.

I understand SDSL stores input given as raw pointers into RAM files internally (does it create a copy?), but the line "unknown file" seems to suggest that something isn't quite right with that. Am I missing something obvious?

SDSL is the latest `master`, compiler/linker is `g++ (Ubuntu 4.9.3-8ubuntu2~14.04) 4.9.3`

**Comment by mpetri** [comment]
Try doing this:

```
 sdsl::construct_im(sa, (const char*)ptr, 1);
```

**Comment by simongog** [comment]
This should fix the issue.
