### ISSUE TITLE
Nothing ever defines HAVE_CXA_DEMANGLE, so names are not demangled in space usage reports

### ISSUE THREAD

**Issue by adamnovak** [simongog/sdsl-lite#317]
The `demangle()` utility function is basically a no-op if `HAVE_CXA_DEMANGLE` is not defined. But nothing in the build system checks to see if name demangling works on the compiler being used; `HAVE_CXA_DEMANGLE` only appears in that one source file in the entire project.

This gives me long ugly names in my space usage report tooltips, which makes the reports hard to use.

Something like https://github.com/OPM/opm-common/blob/master/cmake/Modules/FindCxaDemangle.cmake needs to be pulled in to make cmake see if the demangling code is available. Unfortunately, I don't actually know cmake, so I don't know if I can do this myself.

**Comment by simongog** [comment]
Good point. It seems that only g++ defines the macro. Are you using clang? Thanks for the pointer to the cmake script.

**Comment by adamnovak** [comment]
I am using g++ from GCC 4.9.0. Maybe there's something else you need to do
to get the compiler to define the macro? It's not prefixed with anything;
it seems weird that the compiler would just go and define it by itself.

**Comment by mpetri** [comment]
this should be fixed now.
