### ISSUE TITLE
SDSL Lite Installation

### ISSUE THREAD

**Issue by sanjeevldc** [simongog/sdsl-lite#320]
i am successfully install the SDSL 1.0 but when try to install SDSL lite 2.0 it showing following error:

Library will be installed in '/home/string'
WARNING: .git/hooks directory does not exists.
         The pre-commit hook is not installed.
-- The CXX compiler identification is GNU 4.8.4
-- The C compiler identification is GNU 4.8.4
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Compiler is recent enough to support C++11.
-- Performing Test HAVE_GCC_STD=C__11__WALL__WEXTRA___DNDEBUG
-- Performing Test HAVE_GCC_STD=C__11__WALL__WEXTRA___DNDEBUG - Success
-- Performing Test HAVE_GCC_O3__FFAST_MATH__FUNROLL_LOOPS
-- Performing Test HAVE_GCC_O3__FFAST_MATH__FUNROLL_LOOPS - Success
-- Performing Test HAVE_GCC_MSSE4.2
-- Performing Test HAVE_GCC_MSSE4.2 - Success
-- Found Git: /usr/bin/git (found version "1.9.1") 
git found: /usr/bin/git
fatal: Not a git repository (or any of the parent directories): .git
CMake Error at external/CMakeLists.txt:14 (add_subdirectory):
  The source directory

    /home/string/Documents/sdsl-lite-master/external/libdivsufsort

  does not contain a CMakeLists.txt file.

fatal: Not a git repository (or any of the parent directories): .git
CMake Error at external/CMakeLists.txt:26 (add_subdirectory):
  The source directory

    /home/string/Documents/sdsl-lite-master/external/googletest

  does not contain a CMakeLists.txt file.

-- Looking for C++ include cstdio
-- Looking for C++ include cstdio - found
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring incomplete, errors occurred!
See also "/home/string/Documents/sdsl-lite-master/build/CMakeFiles/CMakeOutput.log".
ERROR: CMake build failed.

**Comment by mpetri** [comment]
did you perform

```
./install.sh
```

or just a cmake .. && make?

**Comment by mpetri** [comment]
Also, what cmake version do you have installed and does the computer you are doing the install on have internet access. It seems like it can't fetch the libdivsufsort submodule from the web.

**Comment by sanjeevldc** [comment]
by .install.sh and cmake version 3.4.3

**Comment by sanjeevldc** [comment]
internet connection is also activated on machine

**Comment by mpetri** [comment]
can you do a git submodule update --init in the main directory?

**Comment by sanjeevldc** [comment]
no  in my machine  gitclone is creting some error host not resolve so i am trying to install by downloading sdsl

**Comment by mpetri** [comment]
well then you have to download 

https://github.com/simongog/libdivsufsort

and place it in the ./externa/ subdirectory.

**Comment by sanjeevldc** [comment]
Library will be installed in '/home/string'
WARNING: .git/hooks directory does not exists.
         The pre-commit hook is not installed.
-- The CXX compiler identification is GNU 4.8.4
-- The C compiler identification is GNU 4.8.4
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Compiler is recent enough to support C++11.
-- Performing Test HAVE_GCC_STD=C__11__WALL__WEXTRA___DNDEBUG
-- Performing Test HAVE_GCC_STD=C__11__WALL__WEXTRA___DNDEBUG - Success
-- Performing Test HAVE_GCC_O3__FFAST_MATH__FUNROLL_LOOPS
-- Performing Test HAVE_GCC_O3__FFAST_MATH__FUNROLL_LOOPS - Success
-- Performing Test HAVE_GCC_MSSE4.2
-- Performing Test HAVE_GCC_MSSE4.2 - Success
-- Found Git: /usr/bin/git (found version "1.9.1") 
git found: /usr/bin/git
CMake Warning (dev) at external/libdivsufsort/CMakeLists.txt:7 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test HAVE_GCC_WALL
-- Performing Test HAVE_GCC_WALL - Success
-- Performing Test HAVE_GCC_FOMIT_FRAME_POINTER
-- Performing Test HAVE_GCC_FOMIT_FRAME_POINTER - Success
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Performing Test HAVE_INLINE
-- Performing Test HAVE_INLINE - Success
-- Performing Test HAVE___INLINE
-- Performing Test HAVE___INLINE - Success
-- Performing Test HAVE___INLINE__
-- Performing Test HAVE___INLINE__ - Success
-- Performing Test HAVE___DECLSPEC_DLLEXPORT_
-- Performing Test HAVE___DECLSPEC_DLLEXPORT_ - Failed
-- Performing Test HAVE___DECLSPEC_DLLIMPORT_
-- Performing Test HAVE___DECLSPEC_DLLIMPORT_ - Failed
-- Check size of uint8_t
-- Check size of uint8_t - done
-- Check size of int32_t
-- Check size of int32_t - done
-- Looking for PRId32
-- Looking for PRId32 - found
-- Check size of int64_t
-- Check size of int64_t - done
-- Looking for PRId64
-- Looking for PRId64 - found
fatal: Not a git repository (or any of the parent directories): .git
CMake Error at external/googletest/CMakeLists.txt:14 (add_subdirectory):
  add_subdirectory given source "libdivsufsort" which is not an existing
  directory.


fatal: Not a git repository (or any of the parent directories): .git
CMake Error at external/googletest/CMakeLists.txt:26 (add_subdirectory):
  add_subdirectory given source "googletest" which is not an existing
  directory.

Now showing this: ...........................
-- Looking for C++ include cstdio
-- Looking for C++ include cstdio - found
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring incomplete, errors occurred!
See also "/home/string/Documents/sdsl-lite-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/string/Documents/sdsl-lite-master/build/CMakeFiles/CMakeError.log".
ERROR: CMake build failed.

**Comment by mpetri** [comment]
so there now is a directory ./external/libdivsufsort/ and the sources for that library are now in there? 

did you do a new `./install.sh` after copying the folder + contents?

**Comment by tb38** [comment]
Probably the other submodule, googletest, is (still) missing.

**Comment by mpetri** [comment]
I don't think googletest is required to install the library. Only tests probably?

**Comment by sanjeevldc** [comment]
yes i do it but same error

**Comment by mpetri** [comment]
why does your git clone produce errors?

**Comment by sanjeevldc** [comment]
sir it may due to proxy server in my institute

**Comment by sanjeevldc** [comment]
sir how it  to be resolve

**Comment by mpetri** [comment]
Like I said, I think if you copy libdivsufsort in the external folder it should work. Can you go to the main sdsl directory and do a `find .` and paste the file listing here?

**Comment by sanjeevldc** [comment]
.
./VERSION
./CMakeModules
./CMakeModules/AppendCompilerFlags.cmake
./CMakeModules/CheckSSE4_2.cmake
./CMakeModules/cmake_uninstall.cmake.in
./CMakeModules/check_mode_ti.cpp
./.gitmodules
./tutorial
./tutorial/document_listing
./tutorial/document_listing/doc_list_index.cpp
./tutorial/document_listing/generate_collection.py
./tutorial/document_listing/Makefile
./tutorial/rmq-example.cpp
./tutorial/expl-03.cpp
./tutorial/expl-24.cpp
./tutorial/expl-25.cpp
./tutorial/expl-01.cpp
./tutorial/int-vector-buffer.cpp
./tutorial/expl-12.cpp
./tutorial/.gitignore
./tutorial/expl-20.cpp
./tutorial/expl-04.cpp
./tutorial/expl-22.cpp
./tutorial/expl-09.cpp
./tutorial/cst-search.cpp
./tutorial/Makefile
./tutorial/expl-07.cpp
./tutorial/cst-traversal.cpp
./tutorial/expl-14.cpp
./tutorial/use-a-wavelet-tree.cpp
./tutorial/expl-11.cpp
./tutorial/expl-26.cpp
./tutorial/csx-printf.cpp
./tutorial/expl-10.cpp
./tutorial/expl-13.cpp
./tutorial/expl-02.cpp
./tutorial/expl-18.cpp
./tutorial/expl-21.cpp
./tutorial/expl-06.cpp
./tutorial/expl-15.cpp
./tutorial/expl-17.cpp
./tutorial/expl-05.cpp
./tutorial/expl-08.cpp
./tutorial/expl-23.cpp
./tutorial/expl-16.cpp
./tutorial/expl-19.cpp
./.travis.yml
./include
./include/CMakeLists.txt
./include/sdsl
./include/sdsl/lcp_bitcompressed.hpp
./include/sdsl/csa_bitcompressed.hpp
./include/sdsl/wt_helper.hpp
./include/sdsl/cst_sct3.hpp
./include/sdsl/rmq_succinct_sada.hpp
./include/sdsl/construct_config.hpp
./include/sdsl/lcp_byte.hpp
./include/sdsl/structure_tree.hpp
./include/sdsl/select_support_scan.hpp
./include/sdsl/coder_comma.hpp
./include/sdsl/lcp_support_tree2.hpp
./include/sdsl/rank_support.hpp
./build/include/sdsl/select_support_scan.hpp
./build/include/sdsl/coder_comma.hpp
./build/include/sdsl/lcp_support_tree2.hpp
./build/include/sdsl/rank_support.hpp
./build/include/sdsl/select_support_mcl.hpp
./build/include/sdsl/iterators.hpp
./build/include/sdsl/coder_elias_gamma.hpp
./build/include/sdsl/lcp_wt.hpp
./build/include/sdsl/suffix_trees.hpp
./build/include/sdsl/rrr_vector.hpp
./build/include/sdsl/wt_pc.hpp
./build/include/sdsl/suffix_arrays.hpp
./build/include/sdsl/bit_vectors.hpp
./build/include/sdsl/memory_management.hpp
./build/include/sdsl/wm_int.hpp
./build/include/sdsl/nearest_neighbour_dictionary.hpp
./build/include/sdsl/sorted_int_stack.hpp
./build/include/sdsl/rrr_vector_15.hpp
./build/include/sdsl/rmq_support_sparse_table.hpp
./build/include/sdsl/bp_support_gg.hpp
./build/include/sdsl/construct_lcp_helper.hpp
./build/include/sdsl/enc_vector.hpp
./build/include/sdsl/config.hpp
./build/include/sdsl/lcp_dac.hpp
./build/include/sdsl/bits.hpp
./build/include/sdsl/qsufsort.hpp
./build/include/sdsl/csa_sampling_strategy.hpp
./build/include/sdsl/uint256_t.hpp
./build/include/sdsl/k2_treap_helper.hpp
./build/include/sdsl/int_vector_mapper.hpp
./build/include/sdsl/ram_filebuf.hpp
./build/include/sdsl/coder_elias_delta.hpp
./build/include/sdsl/rank_support_v.hpp
./build/include/sdsl/cst_iterators.hpp
./build/include/sdsl/lcp_support_tree.hpp
./build/include/sdsl/sfstream.hpp
./build/include/sdsl/cst_fully.hpp
./build/include/sdsl/wt_blcd.hpp
./build/include/sdsl/k2_treap.hpp
./build/include/sdsl/int_vector.hpp
./build/include/sdsl/csa_alphabet_strategy.hpp
./build/include/sdsl/vlc_vector.hpp
./build/include/sdsl/coder_fibonacci.hpp
./build/include/sdsl/suffix_array_algorithm.hpp
./build/include/sdsl/wt_int.hpp
./build/include/sdsl/hyb_vector.hpp
./build/include/sdsl/wavelet_trees.hpp
./build/include/sdsl/int_vector_io_wrappers.hpp
./build/include/sdsl/lcp.hpp
./build/include/sdsl/louds_tree.hpp
./build/include/sdsl/construct_bwt.hpp
./build/include/sdsl/raster_img.hpp
./build/include/sdsl/bp_support_g.hpp
./build/include/sdsl/nn_dict_dynamic.hpp
./build/include/sdsl/construct_lcp.hpp
./build/include/sdsl/wt_algorithm.hpp
./build/include/sdsl/dac_vector.hpp
./build/include/sdsl/sdsl_concepts.hpp
./build/include/sdsl/bit_vector_il.hpp
./build/include/sdsl/wt_ap.hpp
./build/include/sdsl/wt_rlmn.hpp
./build/include/sdsl/construct.hpp
./build/include/sdsl/bp_support_algorithm.hpp
./build/include/sdsl/rrr_helper.hpp
./build/include/sdsl/construct_sa.hpp
./build/include/sdsl/rank_support_scan.hpp
./build/include/sdsl/suffix_array_helper.hpp
./build/include/sdsl/vectors.hpp
./build/include/sdsl/fast_cache.hpp
./build/include/sdsl/construct_sa_se.hpp
./build/include/sdsl/csa_sada.hpp
./build/include/sdsl/CMakeFiles
./build/include/sdsl/coder.hpp
./build/include/sdsl/bp_support.hpp
./build/include/sdsl/sorted_multi_stack_support.hpp
./build/include/sdsl/lcp_vlc.hpp
./build/include/sdsl/inv_perm_support.hpp
./build/include/sdsl/sorted_stack_support.hpp
./build/include/sdsl/csa_wt.hpp
./build/include/sdsl/rank_support_v5.hpp
./build/include/sdsl/wt_hutu.hpp
./build/include/sdsl/io.hpp
./build/include/sdsl/sd_vector.hpp
./build/include/sdsl/suffix_tree_algorithm.hpp
./build/include/sdsl/rmq_succinct_sct.hpp
./build/include/sdsl/rmq_support.hpp
./build/include/sdsl/cst_sada.hpp
./build/include/sdsl/lcp_support_sada.hpp
./build/include/sdsl/ram_fs.hpp
./build/include/sdsl/k2_treap_algorithm.hpp
./build/include/sdsl/wt_gmr.hpp
./build/include/sdsl/uintx_t.hpp
./build/include/sdsl/util.hpp
./build/include/sdsl/select_support.hpp
./build/include/sdsl/construct_isa.hpp
./build/include/sdsl/suffix_tree_helper.hpp
./build/include/sdsl/int_vector_buffer.hpp
./build/include/sdsl/wt_huff.hpp
./build/include/sdsl/uint128_t.hpp
./build/include/sdsl/bp_support_sada.hpp
./build/include/CMakeFiles
./build/.gitignore
./build/test
./build/test/CMakeFiles
./build/CPackConfig.cmake
./build/external
./build/external/libdivsufsort
./build/external/libdivsufsort/CMakeModules
./build/external/libdivsufsort/CMakeModules/cmake_uninstall.cmake
./build/external/libdivsufsort/include
./build/external/libdivsufsort/include/divsufsort.h
./build/external/libdivsufsort/include/divsufsort64.h
./build/external/libdivsufsort/include/config.h
./build/external/libdivsufsort/include/CMakeFiles
./build/external/libdivsufsort/pkgconfig
./build/external/libdivsufsort/pkgconfig/libdivsufsort.pc
./build/external/libdivsufsort/pkgconfig/libdivsufsort64.pc
./build/external/libdivsufsort/pkgconfig/CMakeFiles
./build/external/libdivsufsort/lib
./build/external/libdivsufsort/lib/CMakeFiles
./build/external/libdivsufsort/CMakeFiles
./build/external/CMakeFiles
./build/external/googletest
./build/external/googletest/CMakeFiles
./build/lib
./build/lib/CMakeFiles
./build/CMakeCache.txt
./build/CMakeFiles
./build/CMakeFiles/cmake.check_cache
./build/CMakeFiles/CMakeTmp
./build/CMakeFiles/feature_tests.c
./build/CMakeFiles/feature_tests.bin
./build/CMakeFiles/CheckTypeSize
./build/CMakeFiles/CheckTypeSize/INT32_T.c
./build/CMakeFiles/CheckTypeSize/UINT8_T.bin
./build/CMakeFiles/CheckTypeSize/UINT8_T.c
./build/CMakeFiles/CheckTypeSize/INT32_T.bin
./build/CMakeFiles/CheckTypeSize/INT64_T.bin
./build/CMakeFiles/CheckTypeSize/INT64_T.c
./build/CMakeFiles/feature_tests.cxx
./build/CMakeFiles/3.4.3
./build/CMakeFiles/3.4.3/CMakeCXXCompiler.cmake
./build/CMakeFiles/3.4.3/CMakeDetermineCompilerABI_C.bin
./build/CMakeFiles/3.4.3/CMakeSystem.cmake
./build/CMakeFiles/3.4.3/CompilerIdCXX
./build/CMakeFiles/3.4.3/CompilerIdCXX/CMakeCXXCompilerId.cpp
./build/CMakeFiles/3.4.3/CompilerIdCXX/a.out
./build/CMakeFiles/3.4.3/CompilerIdC
./build/CMakeFiles/3.4.3/CompilerIdC/CMakeCCompilerId.c
./build/CMakeFiles/3.4.3/CompilerIdC/a.out
./build/CMakeFiles/3.4.3/CMakeDetermineCompilerABI_CXX.bin
./build/CMakeFiles/3.4.3/CMakeCCompiler.cmake
./build/CMakeFiles/CMakeError.log
./build/CMakeFiles/CMakeOutput.log
./build/build.sh
./extras
./extras/cheatsheet
./extras/cheatsheet/viz.pdf
./extras/cheatsheet/.gitignore
./extras/cheatsheet/Makefile
./extras/cheatsheet/sdsl-cheatsheet.tex
./extras/cheatsheet/hyperendnotes.sty
./extras/resources
./extras/resources/space-vis.png
./extras/Doxyfile.in
./extras/sdsl.natvis
./extras/literature.bib
./extras/sdsl_definitions.sty
./extras/pre-commit
./extras/sdsl.gdb
./extras/README.md
./benchmark
./benchmark/indexing_extract
./benchmark/indexing_extract/indexes
./benchmark/indexing_extract/indexes/.gitignore
./benchmark/indexing_extract/index.config
./benchmark/indexing_extract/bin
./benchmark/indexing_extract/bin/.gitignore
./benchmark/indexing_extract/visualize
./benchmark/indexing_extract/visualize/extract.R
./benchmark/indexing_extract/visualize/index-filter.config
./benchmark/indexing_extract/visualize/.gitignore
./benchmark/indexing_extract/visualize/Makefile
./benchmark/indexing_extract/visualize/extract.tex
./benchmark/indexing_extract/info
./benchmark/indexing_extract/info/.gitignore
./benchmark/indexing_extract/src
./benchmark/indexing_extract/src/interface.h
./benchmark/indexing_extract/src/info.cpp
./benchmark/indexing_extract/src/run_queries_sdsl.cpp
./benchmark/indexing_extract/src/build_index_sdsl.cpp
./benchmark/indexing_extract/src/genintervals.c
./benchmark/indexing_extract/Makefile
./benchmark/indexing_extract/results
./benchmark/indexing_extract/results/.gitignore
./benchmark/indexing_extract/test_case.config
./benchmark/indexing_extract/intervals
./benchmark/indexing_extract/intervals/.gitignore
./benchmark/indexing_extract/sample.config
./benchmark/indexing_extract/README.md
./benchmark/Make.helper
./benchmark/indexing_locate
./benchmark/indexing_locate/indexes
./benchmark/indexing_locate/indexes/.gitignore
./benchmark/indexing_locate/index.config
./benchmark/indexing_locate/bin
./benchmark/indexing_locate/bin/.gitignore
./benchmark/indexing_locate/visualize
./benchmark/indexing_locate/visualize/index-filter.config
./benchmark/indexing_locate/visualize/.gitignore
./benchmark/indexing_locate/visualize/Makefile
./benchmark/indexing_locate/visualize/locate.tex
./benchmark/indexing_locate/visualize/locate.R
./benchmark/indexing_locate/info
./benchmark/indexing_locate/info/.gitignore
./benchmark/indexing_locate/src
./benchmark/indexing_locate/src/interface.h
./benchmark/indexing_locate/src/info.cpp
./benchmark/indexing_locate/src/run_queries_sdsl.cpp
./benchmark/indexing_locate/src/build_index_sdsl.cpp
./benchmark/indexing_locate/src/pattern_random.cpp
./benchmark/indexing_locate/Makefile
./benchmark/indexing_locate/results
./benchmark/indexing_locate/results/.gitignore
./benchmark/indexing_locate/pattern
./benchmark/indexing_locate/pattern/.gitignore
./benchmark/indexing_locate/test_case.config
./benchmark/indexing_locate/sample.config
./benchmark/indexing_locate/README.md
./benchmark/lcp
./benchmark/lcp/bin
./benchmark/lcp/bin/.gitignore
./benchmark/lcp/visualize
./benchmark/lcp/visualize/lcp-header.tex
./benchmark/lcp/visualize/.gitignore
./benchmark/lcp/visualize/lcp.R
./benchmark/lcp/visualize/Makefile
./benchmark/lcp/visualize/lcp-footer.tex
./benchmark/lcp/.gitignore
./benchmark/lcp/compile_options.config
./benchmark/lcp/lcp.config
./benchmark/lcp/src
./benchmark/lcp/src/.gitignore
./benchmark/lcp/src/create_sa_bwt.cpp
./benchmark/lcp/src/create_lcp.cpp
./benchmark/lcp/Makefile
./benchmark/lcp/results
./benchmark/lcp/results/.gitignore
./benchmark/lcp/test_case.config
./benchmark/lcp/README.md
./benchmark/Make.download
./benchmark/indexing_count
./benchmark/indexing_count/indexes
./benchmark/indexing_count/indexes/.gitignore
./benchmark/indexing_count/index.config
./benchmark/indexing_count/bin
./benchmark/indexing_count/bin/.gitignore
./benchmark/indexing_count/visualize
./benchmark/indexing_count/visualize/index-filter.config
./benchmark/indexing_count/visualize/.gitignore
./benchmark/indexing_count/visualize/Makefile
./benchmark/indexing_count/visualize/count.R
./benchmark/indexing_count/visualize/count-footer.tex
./benchmark/indexing_count/visualize/count-header.tex
./benchmark/indexing_count/info
./benchmark/indexing_count/info/.gitignore
./benchmark/indexing_count/compile_options.config
./benchmark/indexing_count/src
./benchmark/indexing_count/src/interface.h
./benchmark/indexing_count/src/genpatterns.c
./benchmark/indexing_count/src/info.cpp
./benchmark/indexing_count/src/run_queries_sdsl.cpp
./benchmark/indexing_count/src/build_index_sdsl.cpp
./benchmark/indexing_count/Makefile
./benchmark/indexing_count/results
./benchmark/indexing_count/results/.gitignore
./benchmark/indexing_count/pattern
./benchmark/indexing_count/pattern/.gitignore
./benchmark/indexing_count/test_case.config
./benchmark/indexing_count/README.md
./benchmark/data
./benchmark/data/.gitignore
./benchmark/rrr_vector
./benchmark/rrr_vector/block_size.config
./benchmark/rrr_vector/bin
./benchmark/rrr_vector/bin/.gitignore
./benchmark/rrr_vector/visualize
./benchmark/rrr_vector/visualize/rrr-footer.tex
./benchmark/rrr_vector/visualize/.gitignore
./benchmark/rrr_vector/visualize/rrr.R
./benchmark/rrr_vector/visualize/Makefile
./benchmark/rrr_vector/visualize/rrr-header.tex
./benchmark/rrr_vector/compile_options.config
./benchmark/rrr_vector/src
./benchmark/rrr_vector/src/generate_rnd_bitvector.cpp
./benchmark/rrr_vector/src/rrr_time_and_space.cpp
./benchmark/rrr_vector/Makefile
./benchmark/rrr_vector/results
./benchmark/rrr_vector/results/.gitignore
./benchmark/rrr_vector/test_case.config
./benchmark/rrr_vector/README.md
./benchmark/tmp
./benchmark/tmp/.gitignore
./benchmark/self_delimiting_codes
./benchmark/self_delimiting_codes/bin
./benchmark/self_delimiting_codes/bin/.gitignore
./benchmark/self_delimiting_codes/visualize
./benchmark/self_delimiting_codes/visualize/testcase.tex
./benchmark/self_delimiting_codes/visualize/Makefile
./benchmark/self_delimiting_codes/visualize/self_delimiting_codes.tex
./benchmark/self_delimiting_codes/compile_options.config
./benchmark/self_delimiting_codes/src
./benchmark/self_delimiting_codes/src/sdc_benchmark.cpp
./benchmark/self_delimiting_codes/Makefile
./benchmark/self_delimiting_codes/results
./benchmark/self_delimiting_codes/results/.gitignore
./benchmark/self_delimiting_codes/vectors.config
./benchmark/self_delimiting_codes/test_case.config
./benchmark/self_delimiting_codes/README.md
./benchmark/wavelet_trees
./benchmark/wavelet_trees/bin
./benchmark/wavelet_trees/bin/.gitignore
./benchmark/wavelet_trees/visualize
./benchmark/wavelet_trees/visualize/wt-header.tex
./benchmark/wavelet_trees/visualize/wt.R
./benchmark/wavelet_trees/visualize/wt-footer.tex
./benchmark/wavelet_trees/visualize/.gitignore
./benchmark/wavelet_trees/visualize/Makefile
./benchmark/wavelet_trees/wt.config
./benchmark/wavelet_trees/compile_options.config
./benchmark/wavelet_trees/src
./benchmark/wavelet_trees/src/wt_time_and_space.cpp
./benchmark/wavelet_trees/src/gen_bwt.cpp
./benchmark/wavelet_trees/Makefile
./benchmark/wavelet_trees/results
./benchmark/wavelet_trees/results/.gitignore
./benchmark/wavelet_trees/test_case.config
./benchmark/wavelet_trees/README.md
./benchmark/basic_functions.R
./benchmark/suffix_trees
./benchmark/suffix_trees/indexes
./benchmark/suffix_trees/indexes/.gitignore
./benchmark/suffix_trees/stats
./benchmark/suffix_trees/stats/.gitignore
./benchmark/suffix_trees/index.config
./benchmark/suffix_trees/bin
./benchmark/suffix_trees/bin/.gitignore
./benchmark/suffix_trees/visualize
./benchmark/suffix_trees/visualize/.gitignore
./benchmark/suffix_trees/visualize/suffix_trees.R
./benchmark/suffix_trees/visualize/Makefile
./benchmark/suffix_trees/visualize/suffix_trees.tex
./benchmark/suffix_trees/visualize/graph_data.R
./benchmark/suffix_trees/visualize/output
./benchmark/suffix_trees/visualize/output/.gitignore
./benchmark/suffix_trees/compile_options.config
./benchmark/suffix_trees/src
./benchmark/suffix_trees/src/depth_stats.cpp
./benchmark/suffix_trees/src/time_and_space_cst.cpp
./benchmark/suffix_trees/src/build_cst.cpp
./benchmark/suffix_trees/Makefile
./benchmark/suffix_trees/results
./benchmark/suffix_trees/results/.gitignore
./benchmark/suffix_trees/test_case_int.config
./benchmark/suffix_trees/test_case.config
./benchmark/suffix_trees/index_int.config
./benchmark/suffix_trees/README.md
./benchmark/document_retrieval
./benchmark/document_retrieval/indexes
./benchmark/document_retrieval/indexes/.gitignore
./benchmark/document_retrieval/index.config
./benchmark/document_retrieval/bin
./benchmark/document_retrieval/bin/.gitignore
./benchmark/document_retrieval/visualize
./benchmark/document_retrieval/visualize/runtime.R
./benchmark/document_retrieval/visualize/doc_re_time.tex
./benchmark/document_retrieval/visualize/index-filter.config
./benchmark/document_retrieval/visualize/.gitignore
./benchmark/document_retrieval/visualize/index-filter_int.config
./benchmark/document_retrieval/visualize/Makefile
./benchmark/document_retrieval/pattern_length.config
./benchmark/document_retrieval/pattern_length_int.config
./benchmark/document_retrieval/info
./benchmark/document_retrieval/info/.gitignore
./benchmark/document_retrieval/dic.config
./benchmark/document_retrieval/src
./benchmark/document_retrieval/src/word_pat2char_pat.cpp
./benchmark/document_retrieval/src/doc_list_index_sort.hpp
./benchmark/document_retrieval/src/gen_pattern.cpp
./benchmark/document_retrieval/src/size_of_idx.cpp
./benchmark/document_retrieval/src/build_idx.cpp
./benchmark/document_retrieval/src/doc_list_index.hpp
./benchmark/document_retrieval/src/doc_list_index_greedy.hpp
./benchmark/document_retrieval/src/doc_list_index_sada.hpp
./benchmark/document_retrieval/src/query_idx.cpp
./benchmark/document_retrieval/src/doc_list_index_qprobing.hpp
./benchmark/document_retrieval/Makefile
./benchmark/document_retrieval/results
./benchmark/document_retrieval/results/.gitignore
./benchmark/document_retrieval/pattern
./benchmark/document_retrieval/pattern/.gitignore
./benchmark/document_retrieval/dic
./benchmark/document_retrieval/dic/.gitignore
./benchmark/document_retrieval/test_case_int.config
./benchmark/document_retrieval/test_case.config
./benchmark/document_retrieval/index_int.config
./benchmark/document_retrieval/README.md
./benchmark/README.md
./SDSL_INSTALL_PATH
./README.md

**Comment by mpetri** [comment]
there is no content in `./sdsl-master/external/` which is where libdivsufsort is supposed to be instead of `./sdsl-master/build/external/libdivsufsort` where you put it.

**Comment by sanjeevldc** [comment]
so how it be resolve

**Comment by mpetri** [comment]
copy libdivsufsort in the right place and run `./install.sh` again

**Comment by sanjeevldc** [comment]
sir where it will be copied

**Comment by mpetri** [comment]
in `./sdsl-master/external/` so the path becomes `./sdsl-master/external/libdivsufsort`

**Comment by sanjeevldc** [comment]
i already copied it

**Comment by sanjeevldc** [comment]
./external/libdivsufsort
./external/libdivsufsort/LICENSE
./external/libdivsufsort/CMakeModules
./external/libdivsufsort/CMakeModules/AppendCompilerFlags.cmake
./external/libdivsufsort/CMakeModules/CheckFunctionKeywords.cmake
./external/libdivsufsort/CMakeModules/cmake_uninstall.cmake.in
./external/libdivsufsort/CMakeModules/CheckLFS.cmake
./external/libdivsufsort/CMakeModules/ProjectCPack.cmake
./external/libdivsufsort/include
./external/libdivsufsort/include/config.h.cmake
./external/libdivsufsort/include/lfs.h.cmake
./external/libdivsufsort/include/CMakeLists.txt
./external/libdivsufsort/include/divsufsort.h.cmake
./external/libdivsufsort/include/divsufsort_private.h
./external/libdivsufsort/.gitignore
./external/libdivsufsort/pkgconfig
./external/libdivsufsort/pkgconfig/CMakeLists.txt
./external/libdivsufsort/pkgconfig/libdivsufsort.pc.cmake
./external/libdivsufsort/examples
./external/libdivsufsort/examples/unbwt.c
./external/libdivsufsort/examples/suftest.c
./external/libdivsufsort/examples/mksary.c
./external/libdivsufsort/examples/bwt.c
./external/libdivsufsort/examples/CMakeLists.txt
./external/libdivsufsort/examples/sasearch.c
./external/libdivsufsort/CMakeLists.txt
./external/libdivsufsort/VERSION.cmake
./external/libdivsufsort/lib

**Comment by mpetri** [comment]
according to your find output it is in the `./build/` subdirectory. If you copy it to the right place I mentioned it should work. Otherwise I suggest you find a way to use git through your proxy. I can't really help you any further.

**Comment by sanjeevldc** [comment]
sir i have downloaded the sdsllite 2.03 and install it .

it works .

thanks a lot sir...

**Comment by sanjeevldc** [comment]
sir which type of work is carried out by this library . and any tutorial for  beginner beside its chat sheet

**Comment by mpetri** [comment]
there is a tutorial linked in the readme file.

**Comment by mpetri** [comment]
I'm closing this as it seems to be resolved.

**Comment by sanjeevldc** [comment]
ok sir
