### ISSUE TITLE
Impletation Realted to SDSL

### ISSUE THREAD

**Issue by sanjeevldc** [simongog/sdsl-lite#322]
list of application or publication where  SDSL used ?

Is python is easy in comparison to C++ fro beginner to carried out  research in Succinct Data Structure

**Comment by eloj** [comment]
Don't know about apps, but it was used as a baseline in "[Parallel Lightweight Wavelet Tree, Suffix Array
and FM-Index Construction](https://amplab.cs.berkeley.edu/wp-content/uploads/2016/03/dcc2016.pdf)". While I couldn't immediately find it in citeseer, I assume it should be possible to do a citation search for 'From Theory to Practice: Plug and Play with Succinct Data Structures' and get a pretty good idea of papers referencing it.

**Comment by simongog** [comment]
Yes, the google scholar search for the official reference lists some use cases. In addition to that 
https://scholar.google.de/scholar?q=sdsl-lite reveals more applications.
