### ISSUE TITLE
Fails to compile with g++ 4.7.2, but easy to fix

### ISSUE THREAD

**Issue by apirogov** [simongog/sdsl-lite#331]
I have only g++ from the 4.7 series on multiple machines, which is able to compile SDSL in principle, but currently needs a small manual fix with initializer lists that have missing braces:

    diff --git a/include/sdsl/wt_pc.hpp b/include/sdsl/wt_pc.hpp
    index 937f023..06fbba2 100644
    --- a/include/sdsl/wt_pc.hpp
    +++ b/include/sdsl/wt_pc.hpp
    @@ -726,7 +726,7 @@ class wt_pc
              */
             std::array<node_type, 2>
             expand(const node_type& v) const {
    -            return {m_tree.child(v,0), m_tree.child(v,1)};
    +            return {{m_tree.child(v,0), m_tree.child(v,1)}};
             }
     
             //! Returns for each range its left and right child ranges
    @@ -798,8 +798,8 @@ class wt_pc
                 auto right_sp = sp_rank - v_sp_rank;
                 auto left_sp  = r[0] - right_sp;
     
    -            return {{{left_sp, left_sp + left_size - 1},
    -                    {right_sp, right_sp + right_size - 1}
    +            return {{{{left_sp, left_sp + left_size - 1}},
    +                   {{right_sp, right_sp + right_size - 1}}
                     }
                 };
             }

It would be great if you could apply this fix and officially support 4.7!

**Comment by simongog** [comment]
Thanks again @apirogov !
