### ISSUE TITLE
OR, AND, XOR operations for uncompressed bitvectors 

### ISSUE THREAD

**Issue by rsharris** [simongog/sdsl-lite#335]
(different than issue 329)

Am I correct that the current implementation doesn't provide any support for fast bitwise operations on uncompressed bitvectors? I'd like to verify that's true before I attempt to implement it.

My project is using sdsl::bit_vector objects prior to compressing them. I have a need to build related vectors via bit operations (again, prior to compression). Digging into int_vector.hpp it appears the bits in a bitvector are simply stored in a linear array of bytes (or some larger type), so what I'm looking for is something that implements, e.g. ^= by simply performing bytewise xor over the array.

It seems like I can implement this pretty easily but wanted to verify it doesn't already exist before I make that effort.

**Comment by simongog** [comment]
Yes, bitwise xor is not implemented. int_vector is a sequence of uni64_t and it should be easy to add this feature.

**Comment by rsharris** [comment]
Thanks, Simon,

Am about to implement this.  Would that be of general interest for the repo?

**Comment by simongog** [comment]
Sure. This feature is important. The main reason why it is missing is that we usually provide features for all classes of the same concepts, i.e. for all bit vector classes. This enables developers to easily exchange bit vector classes in more complex structures.
But it's fine to start with int_vector. Thanks!

**Comment by rsharris** [comment]
I may have bitten off more than I can chew. What I had in mind is shown below. Intended to go with the other operators in int_vector.hpp.

Two problems though. (1) I'm a C++ novice and am having trouble finding an example of overriding ^= online. My concern is that it isn't supposed to return void. I may also not be using const correctly. (2) I'm not sure what the correct action is in the two cases I've marked as problematic. It would probably be more appropriate to raise an exception than just return. Also I'm allowing the opposite case with capacities, v.capacity() < capacity(), but this assumes any bits beyond the end of a shorter vector can be assumed as zeros, which could be wrong.  Also unclear whether size() would be the correct thing to compare instead of capacity().

void int_vector<t_width>::operator^=(const int_vector& v)const
{
    if (bit_size() != v.bit_size())
        return; <<<--- problematic

    if (v.capacity() > capacity())
        return; <<<--- problematic

    for (uint64_t i=0; i<(v.capacity()>>6); ++i) {
        m_data[i] ^= v.m_data[i];
}

**Comment by simongog** [comment]
Bit vectors of different lengths are problematic. One solution to handle this is to resize the bitvectors to the same size (v only conceptionally by adding zeros to the end).

The method is not const and should return *this (i.e. type `int_vector&`).

**Comment by rsharris** [comment]
I think I've got it, read below.

As I alluded to, my C++ syntax skills are very weak, and my ability to properly hook up library (includes and linking) is also poor. So to test this I grabbed all the stuff I needed from various sdsl-lite files and pulled it into a single cpp file.

Is showing the code here sufficient to get it into some future release?  Or is there more I should do?  E.g. add some self-test code (where?) and/or incorporate this in the package with a clone/push?

I decided to handle the size issues with asserts. I found other code that did it that way.  A shorter v is conceptually extended with zeros.  A longer v fails the assert, and if asserts are off then only the prefix of v is used.

I am not directly verifying that the two operands have the same m_width. It might be desirable to add a check for that.

Possibly the operators should be declared as inline?

Operator prototypes in class int_vector (int_vector.hpp)

int_vector& operator&=(const int_vector& v);
int_vector& operator|=(const int_vector& v);
int_vector& operator^=(const int_vector& v);

and implementations (also in int_vector.hpp)

template<uint8_t t_width>
int_vector<t_width>& int_vector<t_width>::operator&=(const int_vector& v) {
    assert(bit_size() == v.bit_size());
    assert(v.capacity() <= capacity());
    for (uint64_t i=0; i<(v.capacity()>>6); ++i)
        m_data[i] &= v.m_data[i];
    return *this;
    }

template<uint8_t t_width>
int_vector<t_width>& int_vector<t_width>::operator|=(const int_vector& v) {
    assert(bit_size() == v.bit_size());
    assert(v.capacity() <= capacity());
    for (uint64_t i=0; i<(v.capacity()>>6); ++i)
        m_data[i] |= v.m_data[i];
    return *this;
    }

template<uint8_t t_width>
int_vector<t_width>& int_vector<t_width>::operator^=(const int_vector& v) {
    assert(bit_size() == v.bit_size());
    assert(v.capacity() <= capacity());
    for (uint64_t i=0; i<(v.capacity()>>6); ++i)
        m_data[i] ^= v.m_data[i];
    return *this;
    }

**Comment by rsharris** [comment]
This ended up being pull #349.

**Comment by olydis** [comment]
Can this issue be closed? :-)

**Comment by rsharris** [comment]
I would think so.  A pull request for my implementation was accepted -- probably in November (I'd tell you the number but I can't figure out how to find it easily).
