### ISSUE TITLE
gunzip filter at Make.download

### ISSUE THREAD

**Issue by fmontoto** [simongog/sdsl-lite#341]
Hi, I'm trying to download a non gz file to run a benchmark for a datastructure and the script is failing as gunzip does not recognize the extension (of course, it's not a gz file).
I did look into the script and it looks like the Make.download file is not working as I would expect.
This is the script at ```benchmark/Makefile.download```:
```shell
@$(if $(filter-out ".gz",$(FILE)),\
		echo "Extract file $(FILE) using gunzip";\
		gunzip $(FILE))
```
filter-out returns a list of words that does not match the pattern words, and I would expect gunzip to be run when there is a gz file, not when there is none. [filter and filter-out docs](https://www.gnu.org/software/make/manual/html_node/Text-Functions.html)

I'm not a Make expert but I think this would solve the problem.
```shell
@$(if $(filter "%.gz",$(FILE)),\
		echo "Extract file $(FILE) using gunzip";\
		gunzip $(FILE))
```

**Comment by simongog** [comment]
Thanks for the hint. I will adjust the code.

**Comment by fmontoto** [comment]
The code I proposed does not solve the issue, the _"_ around .gz must be removed:
```shell
@$(if $(filter %.gz,$(FILE)),\
        echo "Extract file $(FILE) using gunzip";\
        gunzip $(FILE))
```
Sorry
