### ISSUE TITLE
Error installation

### ISSUE THREAD

**Issue by yifangt** [simongog/sdsl-lite#342]
Hello, when I tried to install sdsl-lite, I met a problem with this error:
```
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [cmTryCompileExec4112205569] Error 1
```

Do you have any clue on this? Thanks a lot!

**Comment by simongog** [comment]
Please make sure that you have libpthread installed on your system. On most systems this is included by default. For this reason it is not explicitly mention in the documentation.

**Comment by yifangt** [comment]
It seem I have them installed.
I noticed the error msg (copy-n-paste) is:
`/usr/bin/ld: cannot find -lpthreads`
you can see it is pthreads instead of pthread.
I am sure it is not a typo from me. Did I miss anything?
