### ISSUE TITLE
Dead code warning due to null reference check

### ISSUE THREAD

**Issue by daniel-j-h** [simongog/sdsl-lite#359]
GCC 6.2 warns about the null reference check [here](https://github.com/simongog/sdsl-lite/blob/7bbb71e8e13279ab45111bd135f4210545cd1c85/include/sdsl/io.hpp#L638).

[8.3.2/5](http://eel.is/c++draft/dcl.ref#5) says a null reference would be Undefined Behavior. The compiler optimizes it away as dead code.

> Note: in particular, a null reference cannot exist in a well-defined program, because the only way to create such a reference would be to bind it to the “object” obtained by indirection through a null pointer, which causes undefined behavior.

I haven't made a PR since I don't now what the original intent behind this was. Please check this.

**Comment by simongog** [comment]
Thanks for your comment @daniel-j-h . The line/check can be removed.

**Comment by amallia** [comment]
Please look at this [PR](https://github.com/simongog/sdsl-lite/pull/360)
