### ISSUE TITLE
RRR problem with clang(?) due to left shift by 64

### ISSUE THREAD

**Issue by rsharris** [simongog/sdsl-lite#365]
The implementation of uint128_t operator>> uses m_high << (64 - x), which fails on some machines when x is zero.  Logically it should result in a zero (since m_high is uint64), but this is either (a) undefined behavior in the c++ spec or (b) a bug in some compilers.

The affect on RRR is that when it attempts to write (into the encoded version of the bit vector) an encoded chunk that needs more than 128 bits, the bits beyond the 128th are wrong. Decode then fails -- in my case I get a burst of 1s at the beginning of the chunk.  Chunks larger than 128 bits wont occur with rrr_vector<127>, but can occur for rrr_vector<255> whenever a chunk has more than 29 ones.

I'm able to test this on three machines. On a *nix using gcc, the code works. On two iMacs using clang, it fails.  On one failing machine, it's clang-800.0.42.1.

The simplest fix, perhaps, is to add a x==0 test at the beginning of operator>>, and just return a copy of the input.

There's some 2013 discussion of what seems to be a similar clang problem for 32 bits, at
   https://bugs.llvm.org//show_bug.cgi?id=17332
This indicates a left shift by the word size is undefined behavior, according to section 5.8pl of *some* document (C or C++ spec?).

I wonder if there are other such left shifts in the  uint128 or uint256 code.  I note that the implementation of uint256_t operator<< contains a TODO note to check for x=128, which may be a similar case.

**Comment by simongog** [comment]
Thanks for opening the issue and proposing the fixes. I will add the extra checks.

**Comment by simongog** [comment]
As you already mentioned, the left shift is defined in Section 5.8 of the [C++ standard](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf) and it is indeed undefined in our case:
> The behavior is undefined if the right operand is negative, or greater than or equal to the length in bits of the promoted left operand.

So I added the proposed checks but also removed the TODOs in uint256_t (as a shift by 0 is defined).
@rsharris  Can you please verify that the code in the issue_365 branch works?

**Comment by rsharris** [comment]
> @rsharris Can you please verify that the code in the issue_365 branch works?

Thanks for the quick response!

It does fix my problem (compiled and verified), but looking at the code I think there could still be a problem in uint128_t operator<<.  If x is 128, doesn't high = m_lo << (x - 64) cause the same problem?

It could be argued that ((uint128_t) v) << 128 is undefined though.  Might be worth putting a comment to that effect in the implementation of uint128_t operator<<.  A similar note would be needed in uint256_t operator<< (a shift of 256 there will have the same problem).

**Comment by simongog** [comment]
> It does fix my problem (compiled and verified), but looking at the code I think there could still be a problem in uint128_t operator<<. If x is 128, doesn't high = m_lo << (x - 64) cause the same problem?

The `shift=128` case is now handled explicitly ;)
Thanks again for reporting!
