### ISSUE TITLE
Calculate the F of WT

### ISSUE THREAD

**Issue by arman4343** [simongog/sdsl-lite#367]
Hello,
I just want to calculate the F array of WT. but I confuse how can i access the F array of WT in SDSL lib.
Can you address some sample code?

**Comment by simongog** [comment]
I'm confused about your question. Do you mean the F array of a compressed suffix array (CSA)??? Please have a look at the cheatsheet for its use.

**Comment by arman4343** [comment]
Thank you very much Mr. Simongog. I found it. Your lib is really great.
