### ISSUE TITLE
rank_support_il.hpp doesn't exist

### ISSUE THREAD

**Issue by orlp** [simongog/sdsl-lite#370]
In [the cheat sheet](http://simongog.github.io/assets/data/sdsl-cheatsheet.pdf) there is a dead link to [rank_support_il](https://github.com/simongog/sdsl-lite/blob/master/include/sdsl/rank_support_il.hpp).

P.S.: there is also a typo in the range min/max query section, 'miniumum'.

**Comment by simongog** [comment]
Thanks for reporting. This is fixed now.
