### ISSUE TITLE
A doubt regarding rrr_vector

### ISSUE THREAD

**Issue by shas19** [simongog/sdsl-lite#373]
Hello sir,
I am experimenting with the size of the rrr_vector for a particular bit_vector. I have read the RRR orginal paper. 
I found that the objects of type rank_support_rrr and select_support_rrr do not take any extra space, as they only store the pointers to the object of type rrr_vector. Now the RRR paper describes two types of dictionaries, Fully indexable dictionary(FID) and Indexable dictionary(Id). FID takes n+o(n) bits where as ID takes space close to theoretical lower bound bits (Depending on number of 1's). The cheat sheet mentions that the rrr_vector takes total space which almost equal to theoretical lower bound. So that means, it must be an ID which only supports rank1 and select1, but without using any extra space I am able to support rank0 support as well as select0 support. how is this possible?
Where in my understanding, I am making mistake?
Thanks,
Shubham

**Comment by mpetri** [comment]
Select1/0 is implemented using binary search over the rank samples

**Comment by shas19** [comment]
In that case, should not  the lower order terms be shown in the cheatsheet, as they will usually dominate the theoretical lower bound term. 
For the FID the lower order term is o(u), where u is the size of universe.

**Comment by mpetri** [comment]
We actually implement this version of RRR: `Gonzalo Navarro, Eliana Providel: Fast, Small, Simple Rank/Select on Bitmaps. SEA 2012: 295-306`

and if you look at this paper `Simon Gog, Matthias Petri: Optimized succinct data structures for massive data. Softw., Pract. Exper. 44(11): 1287-1314 (2014)` , Figure `2` you can see the space breakdown for the different RRR compontents on some "real datasets". 

I agree that the `+o()` term should probably be there but it is a cheatsheet so maybe it doesn't have to be exact.

**Comment by shas19** [comment]
okay..Thanks a lot.
