### ISSUE TITLE
googletest has moved (build is using old URL)

### ISSUE THREAD

**Issue by rsharris** [simongog/sdsl-lite#375]
I did a fresh clone of sdsl-lite today, and the build (make install) failed pretty quickly, because it is trying to get googletest from
   https://chromium.googlesource.com/external/googletest
but that repo is deprecated (according to the readme.md there).

I was able to get around this by doing
  cd sdsl-lite/external
  git clone https://github.com/google/googletest
  (cd back to sdsl-lite)
  ./install.sh

**Comment by mpetri** [comment]
Are you sure? I just checkout out a fresh copy of sdsl-lite and ./install.sh checks out ok with the current googletest url.

**Comment by rsharris** [comment]
Strange.

If I clone that googletest directly from the command line
    git clone https://chromium.googlesource.com/external/googletest
what I end up with is a single file, README.md, which says
  This mirror has been deprecated. The actual repository has moved to
  https://github.com/google/googletest/
  The new mirror of it is
  https://chromium.googlesource.com/external/github.com/google/googletest/

I don't see how the install process could have been successful using that googletest, since it contains no code.

The error that I got when I didn't manually clone googletest:
   ...
  -- Looking for PRId64
  -- Looking for PRId64 - found
  Cloning into 'external/googletest'...
  fatal: unable to access 'https://chromium.googlesource.com/external/googletest/':  gnutls_handshake() failed: Error in the pull function.
  fatal: clone of 'https://chromium.googlesource.com/external/googletest' into submodule path 'external/googletest' failed
  CMake Error at external/CMakeLists.txt:26 (add_subdirectory):
    add_subdirectory given source "googletest" which is not an existing directory.
    ...

This probably indicates some problem other than the fact that the repo is deprecated.  The best I could guess after some googling was that either (a) the version of git (2.7.4 ) on the machine I was trying to build on was too old for that repo, or (b) that machine had a security setup that didn't trust  googlesource.com.  That led me to try cloning the repo on a different machine, at which point I discovered the README.md claim of deprecation.

I had success by cloning googletest manually, from a different URL, as described in my first post.

**Comment by rsharris** [comment]
OK, I just tried a fresh clone and build of sdsl-lite on a different machine, and had no issue.

What I don't understand is how it can work.  If I clone that googletest manually, by
  git clone https://chromium.googlesource.com/external/googletest
I get the deprecation README.md and nothing else.

And if I look at
  https://chromium.googlesource.com/external/googletest
in my web broswer, I see the deprecation message and I also see that all the files have been deleted from the repo.  How is the sdsl-lite clone of this getting any code?

**Comment by mpetri** [comment]
maybe googlesource.com has some magic in their that detects submodule clones and "does the right thing" to not break lots of repos.

However, as you pointed out the repo is deprecated so I think changing the url makes sense. Do you want to do a pull request or should I fix it?

**Comment by mpetri** [comment]
actually, when you add a repo as a submodule it pins it to a specific revision. that's why the checkout should still work. but then why would it fail for you?

**Comment by rsharris** [comment]
> However, as you pointed out the repo is deprecated so I think changing the url
> makes sense. Do you want to do a pull request or should I fix it?

Probably better if you do it.  I don't know where the URL is, in the build process.  I spent a little time trying to find it when I ran into the problem, but I was not successful.

> actually, when you add a repo as a submodule it pins it to a specific revision. that's why
> the checkout should still work. but then why would it fail for you?

I think it fails for me for some other reason, relating to the machine I was trying to build on.  I wasn't manually able to clone from that googlesource repo on that machine either

>    git clone https://chromium.googlesource.com/external/googletest
>    fatal: unable to access 'https://chromium.googlesource.com/external/googletest/':
>    gnutls_handshake() failed: Error in the pull function.

I *was* able to manually clone the version on github on that machine.  And I was able to manually clone from that googlesource repo on another machine.  The machine where it fails is a new setup, though for some reason it has git version 2.7.4 (the latest seems to be 2.13.1).

**Comment by mpetri** [comment]
This was fixed with pr #376
