### ISSUE TITLE
./install.sh seems broken since release 2.1

### ISSUE THREAD

**Issue by dvalenzu** [simongog/sdsl-lite#377]
Hi,

Running 

./install.sh  /path/to/my_local_version/

Gives an error (it worked ok, until version 2.0.3). 
The error output is as follows:

-- Found Git: /usr/bin/git (found version "1.9.1") 
git found: /usr/bin/git
error: pathspec 'ext/sdsl-lite-2.1.1/external/libdivsufsort' did not match any file(s) known to git.
Did you forget to 'git add'?
CMake Error at external/CMakeLists.txt:14 (add_subdirectory):
  The source directory

    /home/dvalenzu/PHD/repos_code/develop/CHIC/ext/sdsl-lite-2.1.1/external/libdivsufsort

  does not contain a CMakeLists.txt file.

error: pathspec 'ext/sdsl-lite-2.1.1/external/googletest' did not match any file(s) known to git.
Did you forget to 'git add'?
CMake Error at external/CMakeLists.txt:26 (add_subdirectory):
  The source directory

    /home/dvalenzu/PHD/repos_code/develop/CHIC/ext/sdsl-lite-2.1.1/external/googletest

  does not contain a CMakeLists.txt file.

-- Looking for C++ include cstdio
-- Looking for C++ include cstdio - found
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.6") 
-- Configuring incomplete, errors occurred!
See also "/home/dvalenzu/PHD/repos_code/develop/CHIC/ext/sdsl-lite-2.1.1/build/CMakeFiles/CMakeOutput.log".
ERROR: CMake build failed.
make: *** [sdsl-local-install/lib/libsdsl.a] Error 1

**Comment by mpetri** [comment]
hmm. your version of `git` seems very old. I just cloned a fresh copy and everything seems fine. Can you run `git submodule update --init external/libdivsufsort` in the sdsl-repo and see what happens?

**Comment by dvalenzu** [comment]
Hi, sorry I failed to specify this; when I clone the project it works fine; the problem occurs when I download the  release, either 2.1 or 2.1.1; when downloading 2.0.3 it works fine,

**Comment by mpetri** [comment]
yes. I think it is because Simon forgot to package the external dependencies (which are added via `git submodule`) into the release package. I will fix this tomorrow by releasing a new version which includes the dependencies.

**Comment by mpetri** [comment]
@dvalenzu I added two "offline install" archives to the 2.1.1 release. Could you check if this now works for you?

**Comment by dvalenzu** [comment]
it works, thanks!
