### ISSUE TITLE
Does dac_vector requires different adjacent values on input? 

### ISSUE THREAD

**Issue by danielsaad** [simongog/sdsl-lite#380]
Hi Simon and all.

I'm sorry if this is not the right place for this kind of question, but is dac_vector really dependent on its input values?
I found this in the documentation, and the pre-requisite is that no two adjacent values should be equal.

```cpp
 //! Constructor for a Container of unsigned integers.
 /*! \param c A container of unsigned integers.
      \pre No two adjacent values should be equal.
  */
   template<class Container>
   dac_vector(const Container& c);
```

I thought dac encoded values were independent from each other.

Best Regards.

**Comment by mpetri** [comment]
I don't think this requirement is true. Have you tried it? From looking at the code it looks like the values are coded independently.

**Comment by danielsaad** [comment]
Hi Mathias. I haven't tested. But Simon replied via e-mail with "Hi Daniel, you're right. The pre-requisite is wrong." I will submit a pull request removing the \pre condition.
