### ISSUE TITLE
Compile problems with sd_vector

### ISSUE THREAD

**Issue by danielsaad** [simongog/sdsl-lite#385]
Hello, SImon and all. 
I had this compilation problem in sd_vector.hpp in g++ 7.2.0

> /home/danielsaad/Códigos/gc-is/include/sdsl/sd_vector.hpp:236:28: error: ‘is_sorted’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
>              if (! is_sorted(begin,end)) {
>                    ~~~~~~~~~^~~~~~~~~~~
> In file included from /usr/include/c++/7.2.0/algorithm:62:0,
>                  from /home/danielsaad/Códigos/gc-is/include/sdsl/util.hpp:45,
>                  from /home/danielsaad/Códigos/gc-is/include/sdsl/int_vector.hpp:26,
>                  from /home/danielsaad/Códigos/gc-is/include/gcis_unary_codec.hpp:9,
>                  from /home/danielsaad/Códigos/gc-is/include/gc-is.hpp:6,
>                  from /home/danielsaad/Códigos/gc-is/src/gc-is-codec.cpp:5:
> /usr/include/c++/7.2.0/bits/stl_algo.h:3223:5: note: ‘template<class _FIter, class _Compare> bool std::is_sorted(_FIter, _FIter, _Compare)’ declared here, later in the translation unit
>      is_sorted(_ForwardIterator __first, _ForwardIterator __last,
>      ^~~~~~~~~

But changing is_sorted for std::is_sorted made the code compile.

**Comment by mpetri** [comment]
Can you create a pull request?

**Comment by danielsaad** [comment]
Sure Matthias. I already did.
Best regards.

**Comment by mpetri** [comment]
Thanks!
