### ISSUE TITLE
k2_tree.hpp uses c++17 exclusive functionallity and won't build on olders compilers

### ISSUE THREAD

**Issue by Fethrblaka** [simongog/sdsl-lite#391]
On line 535 of k2_tree.hpp the functionallity [http://en.cppreference.com/w/cpp/language/structured_binding](url)
is used, for wich gcc-7 and c++17 is neded.

**Comment by tetzank** [comment]
My bad. I opened a pull request to fix it.

**Comment by simongog** [comment]
Thanks @tetzank and @Fethrblaka !
