### ISSUE TITLE
Best way to collect a collection of bit_vectors into one

### ISSUE THREAD

**Issue by amosbird** [simongog/sdsl-lite#394]
Hi, is there a recommended way to do this concatenation? Regards.

**Comment by simongog** [comment]
If you have a collections of many small bit_vectors b_0,...,b_{k-1} than it is a good idea to store the concatenation in one bit_vector B and use one sd_vector to point the start of each b_i in B.
This way you reduce the space from c*k+n bits (where c=64) to about n+2k+k log(n/k)+o(k) bits.

**Comment by amosbird** [comment]
Hmm, I don't follow. How can I concatenate this vector of bit_vectors? Currently I'm doing this
```
            std::vector<bit_vector> bv;
            ...
            
            size_type bv_size = 0;
            for (auto it = bv.begin(); it != bv.end(); it++)
                bv_size += (*it).size();

            bit_vector res(bv_size, 0);
            int n = 0;
            for (auto it = bv.begin(); it != bv.end(); it++)
                for (unsigned i = 0; i < (*it).size(); i++) {
                    res.set_int(n, (*it).get_int(i, 1), 1);
                    n++;
                }
```

**Comment by simongog** [comment]
Ok, I seems that you are fine with the concatenation (so you don't need to store pointers to the start of each bitvector b_i in the concatenation). Then the code is fine. You can simplify:

```
            std::vector<bit_vector> bv;
            ...
            
            size_type bv_size = 0;
            for (auto it = bv.begin(); it != bv.end(); it++)
                bv_size += (*it).size();

            bit_vector res(bv_size, 0);
            int n = 0;
            for (auto it = bv.begin(); it != bv.end(); it++)
                for (unsigned i = 0; i < (*it).size(); i++) {
                    res[n++] = (*it)[i]
                }
```

Assigning the data bit by bit is not very efficient. You could use memcpy on the data() element of the bit_vector if this part of you code is time critical.

**Comment by amosbird** [comment]
Ah, OK. So the concatenated version isn't any different than the original ones. I thought it might be compressed a little bit due to the large amount of bit_vector fragments.

**Comment by simongog** [comment]
Sure, the concatenated version is much smaller if you have many small bit_vectors. Please read first comment above.

**Comment by simongog** [comment]
or consult this tutorial :)
http://pages.di.unipi.it/rossano/wp-content/uploads/sites/7/2016/07/Slide.pdf

**Comment by amosbird** [comment]
Great! Thank you :D
