### ISSUE TITLE
building CSA using disk backed construct on a byte alphabet file

### ISSUE THREAD

**Issue by ekg** [simongog/sdsl-lite#395]
I've been attempting to use disk-backed construction of a byte-width string that I've serialized to disk. It's a big data set (50G) but I have a system with 256G and so I've been surprised to see construction fail with out of memory errors. I had the impression that it was partly disk backed.

Review of the code makes it seem that the non-disk backed approach is prefered for byte alphabets. Am I confused, and if not how could I direct construction to use the less RAM-intensive mode?

**Comment by simongog** [comment]
For strings larger than 2G, each suffix array entry takes 8 instead of 4 bytes. So the `construct` method has a peak of 9 times the input size for byte-width strings. So 450 GB.
You can use the space-efficient SA construction.
Here is an example:
https://github.com/simongog/sdsl-lite/blob/master/examples/sa-construct-space-efficient.cpp

This slows down construction by a factor of about 2 but should only use 2 times the input size ;)

**Comment by simongog** [comment]
```
construct_config::byte_algo_sa = SE_SAIS; // or LIBDIVSUFSORT for less space-efficient but faster construction
```
is what you have to add before calling `construct`.

**Comment by ekg** [comment]
I'll give this a try, thanks!

**Comment by ekg** [comment]
I've tested this, but I end up running out of memory on a 256G system when building the CSA for a 70G input (byte alphabet). The first file is the input, and the rest I guess are intermediates.

```
-rw-r--r--  1 eg10    graphs   70G Dec 22 18:53 .vg-pack_XXxZklP3_0
-rw-r--r--  1 eg10    graphs   70G Dec 22 19:06 text_26880_0.sdsl
-rw-r--r--  1 eg10    graphs   70G Dec 22 19:11 26880_1_text_rec0.sdsl
-rw-r--r--  1 eg10    graphs  8.8G Dec 22 19:58 26880_2_lms_pos_b0.sdsl
-rw-r--r--  1 eg10    graphs  255G Dec 22 20:42 26880_5_lms_positions0.sdsl
-rw-r--r--  1 eg10    graphs     9 Dec 22 20:42 26880_4_left0.sdsl
-rw-r--r--  1 eg10    graphs     9 Dec 22 20:42 26880_3_right0.sdsl
```

I'm building it this way:

```c++
    construct_config::byte_algo_sa = SE_SAIS;
#pragma omp parallel for
    for (size_t i = 0; i < edit_tmpfile_names.size(); ++i) {
        construct(edit_csas[i], edit_tmpfile_names[i], 1);
    }
```

Note that there is only one tempfile in this case. Am I not making this call correctly?
