### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by siweimutong** [simongog/sdsl-lite#408]
error: pathspec 'external/libdivsufsort' did not match any file(s) known to git.
CMake Error at external/CMakeLists.txt:14 (add_subdirectory):
  The source directory

    /home/gxi/下载/mantis-master/sdsl/external/libdivsufsort

  does not contain a CMakeLists.txt file.

error: pathspec 'external/googletest' did not match any file(s) known to git.
CMake Error at external/CMakeLists.txt:26 (add_subdirectory):
  The source directory

    /home/gxi/下载/mantis-master/sdsl/external/googletest

  does not contain a CMakeLists.txt file.
运行命令出现这样的错误，应该要如何解决

**Comment by mpetri** [comment]
you need to do a `git submodule update --init --recursive` in the mantis main directory (I think).

**Comment by siweimutong** [comment]
git found: /usr/bin/git
CMake Error at external/libdivsufsort/CMakeLists.txt:7:
  Parse error.  Expected a command name, got unquoted argument with text
  "<!DOCTYPE".


-- Configuring incomplete, errors occurred!
Thanks.I have solved the previous problem. Now there is this problem again.

**Comment by mpetri** [comment]
all these things seem to be mantis problems not sdsl problems.

**Comment by siweimutong** [comment]
这个mantis中需要sdsl中的文件，其中sdsl的网址为https://github.com/simongog/sdsl-lite-Succinct Data Structure Library这个库本身就没有安装成功。我在这里遇到的问题就是
root@gxi-W560-G10:/home/gxi/下载/mantis-master/include# cd sdsl
root@gxi-W560-G10:/home/gxi/下载/mantis-master/include/sdsl# ./install.sh
Library will be installed in '/root'
Copy pre-commit into .git/hooks
-- The CXX compiler identification is GNU 4.9.4
-- The C compiler identification is GNU 4.9.4
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Compiler is recent enough to support C++11.
-- Performing Test HAVE_GCC_STD=C__11__WALL__WEXTRA__DNDEBUG
-- Performing Test HAVE_GCC_STD=C__11__WALL__WEXTRA__DNDEBUG - Success
-- Performing Test HAVE_GCC_O3__FFAST_MATH__FUNROLL_LOOPS
-- Performing Test HAVE_GCC_O3__FFAST_MATH__FUNROLL_LOOPS - Success
-- Performing Test HAVE_GCC_MSSE4.2__MARCH=NATIVE
-- Performing Test HAVE_GCC_MSSE4.2__MARCH=NATIVE - Success
-- Performing Test HAVE_CLANG_MSSE4.2__MARCH=NATIVE
-- Performing Test HAVE_CLANG_MSSE4.2__MARCH=NATIVE - Success
-- Performing Test HAVE_CXA_DEMANGLE
-- Performing Test HAVE_CXA_DEMANGLE - Success
-- Compiler supports DEMANGLE.
-- Performing Test HAVE_GCC_DHAVE_CXA_DEMANGLE
-- Performing Test HAVE_GCC_DHAVE_CXA_DEMANGLE - Success
-- Found Git: /usr/bin/git (found version "2.7.4") 
git found: /usr/bin/git
CMake Error at external/libdivsufsort/CMakeLists.txt:7:
  Parse error.  Expected a command name, got unquoted argument with text
  "<!DOCTYPE".


-- Configuring incomplete, errors occurred!
See also "/home/gxi/下载/mantis-master/include/sdsl/build/CMakeFiles/CMakeOutput.log".
ERROR: CMake build failed.
之后我进入mantis中运行，按照mantis的运行步骤。
root@gxi-W560-G10:/home/gxi/下载/mantis-master/include/sdsl# cd ..
root@gxi-W560-G10:/home/gxi/下载/mantis-master/include# cd ..
root@gxi-W560-G10:/home/gxi/下载/mantis-master# cd build
root@gxi-W560-G10:/home/gxi/下载/mantis-master/build# make install
[  8%] Building CXX object src/CMakeFiles/mantis_core.dir/query.cc.o
In file included from /home/gxi/下载/mantis-master/src/query.cc:51:0:
/home/gxi/下载/mantis-master/include/coloreddbg.h:33:32: fatal error: sdsl/bit_vectors.hpp: 没有那个文件或目录
 #include "sdsl/bit_vectors.hpp"
                                ^
compilation terminated.
src/CMakeFiles/mantis_core.dir/build.make:88: recipe for target 'src/CMakeFiles/mantis_core.dir/query.cc.o' failed
make[2]: *** [src/CMakeFiles/mantis_core.dir/query.cc.o] Error 1
CMakeFiles/Makefile2:129: recipe for target 'src/CMakeFiles/mantis_core.dir/all' failed
make[1]: *** [src/CMakeFiles/mantis_core.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
就有了以下的提示。
我自己不知道是在哪一步出来问题。感谢您的关注和回答。
非常感谢。
