### ISSUE TITLE
Mantis 执行这个命令的时候遇到这个问题。

### ISSUE THREAD

**Issue by siweimutong** [simongog/sdsl-lite#409]
root@gxi-W560-G10:/home/gxi/下载/mantis-master/build# make install
Scanning dependencies of target mantis_core
[  8%] Building CXX object src/CMakeFiles/mantis_core.dir/kmer.cc.o
[ 16%] Building CXX object src/CMakeFiles/mantis_core.dir/hashutil.cc.o
[ 25%] Building CXX object src/CMakeFiles/mantis_core.dir/query.cc.o
In file included from /home/gxi/下载/mantis-master/src/query.cc:51:0:
/home/gxi/下载/mantis-master/include/coloreddbg.h:33:32: fatal error: sdsl/bit_vectors.hpp: 没有那个文件或目录
 #include "sdsl/bit_vectors.hpp"
                                ^
compilation terminated.
src/CMakeFiles/mantis_core.dir/build.make:88: recipe for target 'src/CMakeFiles/mantis_core.dir/query.cc.o' failed
make[2]: *** [src/CMakeFiles/mantis_core.dir/query.cc.o] Error 1
CMakeFiles/Makefile2:129: recipe for target 'src/CMakeFiles/mantis_core.dir/all' failed
make[1]: *** [src/CMakeFiles/mantis_core.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
请问要怎么解决？

**Comment by mpetri** [comment]
This also seems to be a mantis problem not an sdsl issue.
