### ISSUE TITLE
how to start working with the sdsl?

### ISSUE THREAD

**Issue by ofiramit** [simongog/sdsl-lite#419]
HI.
i have an issue with starting working with the sdsl.
installation was fine, but we did not succeed run it.
we opened new file progran.cpp as in the complie line (g++ -std=c++11 -O3 -DNDEBUG -I ~/include -L ~/lib program.cpp -o program -lsdsl -ldivsufsort -ldivsufsort64) and we written there the getting started code. 
the problem is that the terminal said is: "program.cpp:1:10: fatal error: sdsl/suffix_arrays.hpp: No such file or directory"
and we can fix it locally by fixing the path to be like in our computer, but then it have many more or path fixing and we think its not the right way to do it.

**Comment by manuelVzla01** [comment]
Hi bro 
[programs.tar.gz](https://github.com/simongog/sdsl-lite/files/3986219/programs.tar.gz)
create a folder in my case programs, and within it a .cpp with a makefile, from console stop there and just make, I'll give it to you
