### ISSUE TITLE
problem with serialization of a sd_vector

### ISSUE THREAD

**Issue by PandorasRed** [simongog/sdsl-lite#451]
hello,
i try to serialize and deserialize a sd_vector in my project, and when i try to use it after deserialization  i have a segmentation fault that appear and i don't understand where the problem is. my current code is just 

m_sequence.serialize(output); with output the ostream that is open to write in the file i want

sdsl::sd_vector<> tmp;
tmp.load(input); with input the istream that contain the file with the serialized sd_vector in it

any idea to why it do that?

**Comment by jorgehermo9** [comment]
using store_to_file(tmp,filename) for saving data and then loading data with load_from_file(tmp,filename) works fine to me with sd_vectors. If you're using files, you dont need to serialize and deserialize from osstreams

**Comment by PandorasRed** [comment]
totally miss these function, thank for the help it work now
